'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'nl' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  nl: {
    // Navbar
    'nav.home': 'Home',
    'nav.about': 'Over Mij',
    'nav.portfolio': 'Portfolio',
    'nav.events': 'Events',
    'nav.article': 'Artikelen',

    // Hero Section
    'hero.welcome': 'Welkom in mijn',
    'hero.portfolio': 'digitale portfolio',
    'hero.role1': 'Full Stack Developer',
    'hero.role2': 'UI/UX Enthusiast',
    'hero.role3': 'Cybersecurity Enthusiast',
    'hero.description1': 'Ik transformeer ideeën naar',
    'hero.description1.highlight': 'digitale realiteit',
    'hero.description2': 'Als IT-student en passionate developer bouw ik moderne webapplicaties die niet alleen mooi zijn, maar ook',
    'hero.description2.highlight': 'innovatief en gebruiksvriendelijk',
    'hero.description3': 'Gespecialiseerd in React, TypeScript, Node.js en moderne web technologieën.',
    'hero.downloadCV': 'Download CV',
    'hero.follow': 'Te vinden op:',

    // About Section
    'about.title': 'Over Mij',
    'about.subtitle': 'Met een passie voor technologie en innovatie, ontwikkel ik moderne webapplicaties die gebruikerservaring en functionaliteit perfect combineren.',
    'about.frontend': 'Frontend Development',
    'about.frontend.desc': 'React, TypeScript, Next.js, Tailwind CSS',
    'about.backend': 'Backend Development',
    'about.backend.desc': 'Node.js, Python, Databases, API Design',
    'about.uiux': 'UI/UX Design',
    'about.uiux.desc': 'Figma, Prototyping, User Research, Design Systems',
    'about.projects': 'Projects',
    'about.projects.desc': 'Ontdek mijn innovatieve projecten van e-commerce platforms tot portfolio dashboards.',
    'about.experience': 'Experience',
    'about.experience.desc': 'Jaren ervaring in het bouwen van schaalbare webapplicaties met moderne technologieën.',
    'about.passion': 'Passion',
    'about.passion.desc': 'Gedreven door perfectie en altijd op zoek naar nieuwe uitdagingen in de digitale wereld.',
    'about.tech': 'Technologieën & Tools',

    // Skills Section
    'skills.title': 'Mijn Skills',
    'skills.subtitle': 'Een overzicht van mijn technische vaardigheden en expertise in verschillende gebieden van softwareontwikkeling.',
    'skills.learning.title': 'Altijd Leren & Groeien',
    'skills.learning.desc': 'Technologie evolueert constant, en ik ook. Ik ben altijd bezig met het leren van nieuwe frameworks, tools en best practices om voorop te blijven lopen in de wereld van webontwikkeling.',

    // Portfolio Section
    'portfolio.title': 'Mijn Portfolio',
    'portfolio.subtitle': 'Een selectie van mijn meest recente en innovatieve projecten die moderne technologieën en creatieve oplossingen combineren.',
    'portfolio.featured': 'Featured Projects',
    'portfolio.other': 'Andere Projecten',
    'portfolio.keyFeatures': 'Key Features:',
    'portfolio.viewProject': 'View Project',
    'portfolio.cta.title': 'Geïnteresseerd in samenwerking?',
    'portfolio.cta.subtitle': 'Laten we samen iets geweldigs bouwen. Neem contact op voor meer informatie over mijn projecten.',
    'portfolio.cta.button': 'Bekijk Alle Projecten',

    // Contact Section
    'contact.title': 'Laten we samenwerken',
    'contact.subtitle': 'Heb je een interessant project, een vraag over mijn werk, of wil je gewoon een gesprek? Ik hoor graag van je en ben altijd open voor nieuwe uitdagingen!',
    'contact.form.title': 'Stuur een bericht',
    'contact.form.name': 'Naam',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Onderwerp',
    'contact.form.message': 'Bericht',
    'contact.form.send': 'Verstuur Bericht',
    'contact.info': 'Contact Informatie',
    'contact.email': 'Email',
    'contact.email.desc': 'Voor projecten en samenwerking',
    'contact.linkedin': 'LinkedIn',
    'contact.linkedin.desc': 'Professioneel netwerk',
    'contact.github': 'GitHub',
    'contact.github.desc': 'Bekijk mijn code',
    'contact.availability': 'Beschikbaarheid',
    'contact.available': 'Beschikbaar voor nieuwe projecten',
    'contact.available.desc': 'Ik reageer meestal binnen 24 uur op berichten en ben altijd geïnteresseerd in uitdagende projecten.',
    'contact.expect': 'Wat kun je verwachten?',
    'contact.expect1': 'Snelle en professionele reactie',
    'contact.expect2': 'Transparante communicatie over project scope',
    'contact.expect3': 'Hoge kwaliteit code en design',
    'contact.expect4': 'Ondersteuning na oplevering',
    'contact.cta.title': 'Klaar om je idee werkelijkheid te maken?',
    'contact.cta.subtitle': 'Van concept tot realisatie - laten we samen iets geweldigs bouwen dat impact maakt.',
    'contact.cta.start': 'Start een Project',
    'contact.cta.portfolio': 'Bekijk Portfolio',

    // Footer Section
    'footer.description': 'Full-stack developer & UI/UX designer met een passie voor het bouwen van innovatieve digitale oplossingen.',
    'footer.quickLinks': 'Quick Links',
    'footer.technologies': 'Technologies',
    'footer.services': 'Diensten',
    'footer.specialties': 'Specialiteiten',
    'footer.services.web': 'Web Development',
    'footer.services.uiux': 'UI/UX Design',
    'footer.services.app': 'App Development',
    'footer.services.consulting': 'Consulting',
    'footer.spec.webapps': 'Web Apps',
    'footer.spec.uiux': 'UI/UX Design',
    'footer.spec.fullstack': 'Frontend & Backend',
    'footer.spec.databases': 'Databases',
    'footer.spec.apis': 'API\'s',
    'footer.spec.webapplications': 'Webapplicaties',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.copyright': '© 2025 Wishant Bhajan. Alle rechten voorbehouden.',

    // AboutMe Section (Homepage)
    'aboutme.intro1': 'Hoi! Ik ben Wishant, een gepassioneerde full-stack developer die moderne, innovatieve webapplicaties bouwt. Met expertise in React, TypeScript en Node.js breng ik ideeën tot leven.',
    'aboutme.intro2': 'Van concept tot deployment - ik ontwikkel complete oplossingen met oog voor design, performance en gebruikerservaring.',
    'aboutme.frontend.title': 'Frontend',
    'aboutme.frontend.text': 'React, TypeScript, Next.js',
    'aboutme.backend.title': 'Backend',
    'aboutme.backend.text': 'Node.js, Express, PostgreSQL',
    'aboutme.uiux.title': 'UI/UX Design',
    'aboutme.uiux.text': 'Figma, Tailwind, Responsive Design',
    'aboutme.readMore': 'Lees meer over mij',

    // Contact Section (Homepage)
    'contact.connect': 'Let\'s Connect',
    'contact.intro': 'Open voor nieuwe projecten en samenwerkingen. Neem gerust contact op voor een gesprek over uw volgende digitale oplossing.',
    'contact.phone': 'Telefoon',
    'contact.availability.status': 'Beschikbaar voor freelance projecten',

    // Portfolio Section (Homepage)
    'portfolio.header': 'Featured Projects',
    'portfolio.description': 'Cutting-edge solutions met moderne technologieën en innovatieve designs',
    'portfolio.filter.all': 'All Projects',
    'portfolio.filter.web': 'Web Apps',
    'portfolio.filter.ai': 'AI/ML',
    'portfolio.filter.blockchain': 'Blockchain',
    'portfolio.filter.data': 'Data Viz',
    'portfolio.status.live': 'LIVE',
    'portfolio.status.development': 'DEVELOPMENT',
    'portfolio.status.completed': 'COMPLETED',
    'portfolio.demo': 'Live Demo',
    'portfolio.github.link': 'GitHub',
    'portfolio.techTooltip': 'Click to filter',
    'portfolio.moretech': 'more',
    'portfolio.cta.header': 'Geïnteresseerd in een samenwerking?',
    'portfolio.cta.description': 'Laten we samen iets geweldigs bouwen. Neem contact op voor projecten, samenwerkingen of gewoon een gesprek over technologie.',
    'portfolio.homepage.cta.button': 'Start een Project',

    // Project Data
    'project1.title': 'E-commerce Platform',
    'project1.desc': 'Modern webshop met AI-powered recommendations',
    'project1.extDesc': 'Een volledig functionele webshop met React, Node.js en Stripe integratie. Bevat gebruikersbeheer, productcatalogus, winkelwagen en veilige betalingen.',
    'project1.feature1': 'Responsive Design',
    'project1.feature2': 'Payment Integration',
    'project1.feature3': 'User Authentication',
    'project1.feature4': 'Admin Dashboard',
    'project2.title': 'AI Dashboard',
    'project2.desc': 'Real-time analytics met machine learning',
    'project2.extDesc': 'Interactive dashboard voor portfolio management met real-time data visualisatie, analytics en content management systeem.',
    'project2.feature1': 'Real-time Analytics',
    'project2.feature2': 'Content Management',
    'project2.feature3': 'Data Visualization',
    'project2.feature4': 'Multi-user Support',
    'project3.title': 'Blockchain Wallet',
    'project3.desc': 'Secure crypto wallet met multi-chain support',
    'project3.feature1': 'Multi-chain',
    'project3.feature2': 'Hardware Wallet',
    'project3.feature3': 'DeFi Integration',
    'project4.title': 'Task Management',
    'project4.desc': 'Productivity app met AI assistant',
    'project4.feature1': 'Drag & Drop',
    'project4.feature2': 'Team Collaboration',
    'project4.feature3': 'AI Suggestions',
    'project5.title': 'Weather Dashboard',
    'project5.desc': 'Real-time weather met predictive analytics',
    'project5.feature1': 'Interactive Maps',
    'project5.feature2': 'Forecasting',
    'project5.feature3': 'Alerts',
    'project6.title': 'Social Platform',
    'project6.desc': 'Next-gen social media met privacy focus',
    'project6.feature1': 'End-to-end Encryption',
    'project6.feature2': 'Live Chat',
    'project6.feature3': 'Stories',

    // Skills Categories
    'skills.category.frontend': 'Frontend Development',
    'skills.category.backend': 'Backend Development',
    'skills.category.tools': 'Tools & Technologies',
    'skills.category.languages': 'Programming Languages',

    // ContactPage
    'contactpage.hero.title': 'Let\'s Connect',
    'contactpage.hero.subtitle': 'Heb je een project in gedachten? Laten we samen iets geweldigs bouwen.',
    'contactpage.form.title': 'Send a Message',
    'contactpage.form.name.label': 'Name',
    'contactpage.form.name.placeholder': 'John Doe',
    'contactpage.form.email.label': 'Email',
    'contactpage.form.email.placeholder': 'john@example.com',
    'contactpage.form.subject.label': 'Subject',
    'contactpage.form.subject.placeholder': 'Select a subject',
    'contactpage.form.subject.project': 'New Project',
    'contactpage.form.subject.collaboration': 'Collaboration',
    'contactpage.form.subject.consultation': 'Consultation',
    'contactpage.form.subject.other': 'Other',
    'contactpage.form.message.label': 'Message',
    'contactpage.form.message.placeholder': 'Tell me about your project...',
    'contactpage.form.submit': 'Send Message',
    'contactpage.form.sending': 'Sending...',
    'contactpage.form.success': 'Message sent successfully!',
    'contactpage.form.error': 'Something went wrong. Please try again.',
    'contactpage.info.title': 'Get in Touch',
    'contactpage.info.location': 'Location',
    'contactpage.info.netherlands': 'Netherlands',
    'contactpage.social.title': 'Connect on Social',
    'contactpage.social.twitter': 'Twitter',
    'contactpage.social.discord': 'Discord',
    'contactpage.availability.title': 'Currently Available',
    'contactpage.availability.desc': 'I\'m open for freelance projects and full-time opportunities. Response time: usually within 24 hours.',
    'contactpage.faq.title': 'Frequently Asked Questions',
    'contactpage.faq.subtitle': 'Antwoorden op veelgestelde vragen',
    'contactpage.faq1.q': 'What services do you offer?',
    'contactpage.faq1.a': 'Full stack web development, UI/UX design, API development, security auditing, and technical consulting.',
    'contactpage.faq2.q': 'What is your typical project timeline?',
    'contactpage.faq2.a': 'Project timelines vary based on complexity. Small projects: 2-4 weeks, Medium: 1-3 months, Large: 3-6 months.',
    'contactpage.faq3.q': 'Do you work remotely?',
    'contactpage.faq3.a': 'Yes! I work with clients globally and am comfortable with remote collaboration tools and async communication.',
    'contactpage.faq4.q': 'What are your rates?',
    'contactpage.faq4.a': 'Rates depend on project scope and complexity. Contact me for a custom quote tailored to your needs.',

    // AboutPage
    'aboutpage.hero.title': 'Over Mij',
    'aboutpage.hero.subtitle': 'Een gepassioneerde Full Stack Developer met focus op cybersecurity, moderne web technologieën en het creëren van innovatieve digitale ervaringen.',
    'aboutpage.role.developer': 'Developer',
    'aboutpage.role.designer': 'Designer',
    'aboutpage.role.innovator': 'Innovator',
    'aboutpage.role.problemsolver': 'Problem Solver',
    'aboutpage.tab.journey': 'Mijn Reis',
    'aboutpage.tab.expertise': 'Expertise',
    'aboutpage.tab.values': 'Waarden',
    'aboutpage.journey.2020.event': 'Begonnen met programmeren',
    'aboutpage.journey.2020.desc': 'Eerste stappen in web development',
    'aboutpage.journey.2021.event': 'Deep dive in React & TypeScript',
    'aboutpage.journey.2021.desc': 'Moderne frontend frameworks',
    'aboutpage.journey.2022.event': 'Full Stack Development',
    'aboutpage.journey.2022.desc': 'Backend, databases en cloud',
    'aboutpage.journey.2023.event': 'Cybersecurity Focus',
    'aboutpage.journey.2023.desc': 'Secure coding practices',
    'aboutpage.journey.2024.event': 'UI/UX Specialist',
    'aboutpage.journey.2024.desc': 'Design systems en user experience',
    'aboutpage.expertise.frontend': 'Frontend Architecture',
    'aboutpage.expertise.backend': 'Backend Development',
    'aboutpage.expertise.cybersecurity': 'Cybersecurity',
    'aboutpage.expertise.uiux': 'UI/UX Design',
    'aboutpage.expertise.devops': 'DevOps & Cloud',
    'aboutpage.value.security.title': 'Security First',
    'aboutpage.value.security.desc': 'Elke lijn code met beveiliging in gedachten',
    'aboutpage.value.performance.title': 'Performance',
    'aboutpage.value.performance.desc': 'Snelle, geoptimaliseerde applicaties',
    'aboutpage.value.ux.title': 'User Experience',
    'aboutpage.value.ux.desc': 'Intuïtieve en mooie interfaces',
    'aboutpage.value.innovation.title': 'Innovation',
    'aboutpage.value.innovation.desc': 'Altijd op zoek naar betere oplossingen',
    'aboutpage.cta.title': 'Laten We Samen Bouwen',
    'aboutpage.cta.subtitle': 'Op zoek naar een developer die jouw visie kan realiseren?',
    'aboutpage.cta.button': 'Bekijk Portfolio',

    // Featured Projects & Skills Section
    'featured.projects.title': 'Uitgelichte Projecten',
    'featured.projects.description': 'Geavanceerde oplossingen met moderne technologieën',
    'featured.skills.title': 'Technische Vaardigheden',
    'featured.skills.description': 'Expertise in moderne technologieën en frameworks',
    'featured.viewAllProjects': 'Bekijk Alle Projecten',

    // Project Cards - Real Projects
    'featured.wishshield.desc': 'Vulnerability scanner voor OWASP Top 10 risico\'s',
    'featured.tabletech.desc': 'Restaurant software voor horecabedrijven',
    'featured.calendify.desc': 'Kantoorkalender voor hybride werkplekken',
    'featured.wishguard.desc': 'Security monitoring systeem',
    'featured.cryptobot.desc': 'Crypto trading bot met AI algoritmes',
    'featured.urbanmobility.desc': 'Stedelijke mobiliteitsoplossing',

    // Project Labels
    'featured.label.cybersecurity': 'Cybersecurity',
    'featured.label.live': 'Live',
    'featured.label.personal': 'Persoonlijk',
    'featured.label.comingSoon': 'Binnenkort',

    // Skills
    'featured.skill.ai': 'Alle Programmeertalen',
    'featured.skill.ai.note': 'Ik weet hoe ik met AI moet praten',
    'featured.skill.react': 'React / Next.js',
    'featured.skill.typescript': 'TypeScript',
    'featured.skill.csharp': 'C#',
    'featured.skill.nodejs': 'Node.js',
    'featured.skill.python': 'Python',
    'featured.skill.cybersecurity': 'Cybersecurity',
    'featured.skill.cybersecurity.note': 'Actief aan het ontwikkelen',
    'featured.skill.databases': 'Databases',
    'featured.skill.docker': 'Docker / K8s',
    'featured.skill.ml': 'Machine Learning',
    'featured.skill.other': 'Overige technologieën',

    // Skill Categories
    'featured.category.ai': 'AI',
    'featured.category.frontend': 'Frontend',
    'featured.category.backend': 'Backend',
    'featured.category.security': 'Security',
    'featured.category.database': 'Database',
    'featured.category.devops': 'DevOps',
    'featured.category.tools': 'Tools',

    // Skill Stats
    'featured.stats.technologies': 'Technologieën',
    'featured.stats.experience': 'Jaar Ervaring',
    'featured.stats.projects': 'Projecten',

    // About Section (Homepage)
    'aboutsection.title': 'Over Mij',
    'aboutsection.subtitle': '3e jaars Informatica student met een passie voor cybersecurity en innovatieve weboplossingen. Ik combineer creativiteit met technische expertise om veilige en gebruiksvriendelijke applicaties te bouwen.',
    'aboutsection.terminal.name': 'Naam: Wishant Bhajan',
    'aboutsection.terminal.age': 'Leeftijd: 20',
    'aboutsection.terminal.location': 'Locatie: Rotterdam, NL',
    'aboutsection.terminal.role': 'Rol: Student Informatica 3e jaars',
    'aboutsection.terminal.status': 'Status: Beschikbaar voor werk',
    'aboutsection.terminal.passion': 'Passie: Cybersecurity & Innovatie',
    'aboutsection.terminal.experience': 'Ervaring: 3+ jaar',
    'aboutsection.button': 'Meer Over Mij',
    'aboutsection.profilecard.name': 'Wishant Bhajan',
    'aboutsection.profilecard.title': 'Software Engineer',
    'aboutsection.profilecard.status': 'Beschikbaar voor werk',
    'aboutsection.profilecard.contact': 'Contact',

    // Portfolio Page
    'portfoliopage.title': 'Mijn Portfolio',
    'portfoliopage.subtitle': 'Ontdek mijn projecten en werk',
    'portfoliopage.search': 'Zoek projecten...',
    'portfoliopage.tier.all': 'Alle Tiers',
    'portfoliopage.tier.i': 'Tier I',
    'portfoliopage.tier.ii': 'Tier II',
    'portfoliopage.tier.iii': 'Tier III',
    'portfoliopage.subcategory.all': 'Alles',
    'portfoliopage.subcategory.websites': 'Websites',
    'portfoliopage.subcategory.crypto': 'Crypto',
    'portfoliopage.subcategory.systems': 'Systemen',
    'portfoliopage.category.cybersecurity': 'Cybersecurity',
    'portfoliopage.category.bedrijven': 'Bedrijven',
    'portfoliopage.category.persoonlijk': 'Persoonlijk',
    'portfoliopage.backToCategories': 'Terug naar Categorieën',
    'portfoliopage.projects': 'projecten',
    'portfoliopage.project': 'project',
    'portfoliopage.noProjects': 'Nog geen projecten in deze categorie.',
    // Project Card
    'project.comingSoon': 'Binnenkort Beschikbaar',
    'project.github': 'GitHub',
    'project.liveDemo': 'Live Demo',
    // Project Modal
    'project.modal.featuredProject': 'Uitgelicht Project',
    'project.modal.technologies': 'Technologieën',
    'project.modal.viewOnGitHub': 'Bekijk op GitHub',
    'project.modal.viewLiveDemo': 'Live Demo',
    'project.modal.caseStudy': 'Case Study',
    'project.modal.close': 'Sluiten',
    // Cybersecurity Modal
    'project.modal.cybersecurity.title': 'Binnenkort Beschikbaar',
    'project.modal.cybersecurity.message': 'Dit project is afgerond, maar wordt momenteel nog verwerkt voor presentatie.',
    'project.modal.cybersecurity.understood': 'Begrepen',
    // Pending Info Modal
    'project.modal.pending.message': 'Dit project is afgerond. De projectinformatie wordt binnenkort toegevoegd aan deze pagina.',
    'project.modal.pending.viewWebsite': 'Bekijk de live website:',
    'project.modal.pending.understood': 'Begrepen',

    // Event/Calendify Page
    'eventpage.title': 'Events & Hackathons',
    'eventpage.subtitle': 'Ontdek mijn journey door verschillende tech events, hackathons en workshops waar ik heb deelgenomen en nieuwe skills heb geleerd.',
    'eventpage.filter.all': 'Alles',
    'eventpage.filter.hackathon': 'Hackathon',
    'eventpage.filter.conference': 'Conference',
    'eventpage.filter.workshop': 'Workshop',
    'eventpage.filter.competition': 'Competition',
    'eventpage.modal.highlights': 'Highlights',
    'eventpage.modal.technologies': 'Technologieën',
    'eventpage.modal.moreinfo': 'Meer Info',
    'eventpage.empty': 'Geen events gevonden in deze categorie.',
    'eventpage.cta.title': 'Wil je samen naar een event?',
    'eventpage.cta.subtitle': 'Ik ben altijd op zoek naar nieuwe hackathons en tech events om bij te wonen.',
    'eventpage.more': 'meer',
    'eventpage.filter.cybersecurity': 'Cybersecurity',
    'eventpage.filter.ai': 'AI',
    'eventpage.filter.blockchain': 'Blockchain',
    'eventpage.filter.other': 'Overig',
    'eventpage.myExperience': 'Mijn Ervaring',
    'eventpage.myExpectations': 'Mijn Verwachtingen',
    'eventpage.upcomingEvent': 'Aankomend Event',
    'eventpage.allEvents': 'Alle events',
    'eventpage.aboutEvent': 'Over dit event',
    'eventpage.highlights': 'Hoogtepunten',
    'eventpage.photosVideos': "Foto's & Video's",
    'eventpage.photosVideosSoon': "Foto's & video's komen binnenkort...",
    'eventpage.whatILearned': 'Wat ik heb geleerd',
    'eventpage.whatIWantToLearn': 'Wat Ik Wil Leren (verwacht / leerdoelen)',
    'eventpage.conclusion': 'Conclusie',
    'eventpage.date': 'Datum',
    'eventpage.location': 'Locatie',
    'eventpage.category': 'Categorie',
    'eventpage.participants': 'Deelnemers',
    'eventpage.otherEvents': 'Andere events waar ik ben geweest',
    'eventpage.viewDetails': 'Bekijk details',
    'eventpage.viewAllEvents': 'Bekijk alle events',
    'eventpage.noEventsFound': 'Geen events gevonden in deze categorie',
    'eventpage.close': 'Sluiten (Escape)',
    'eventpage.previous': 'Vorige',
    'eventpage.next': 'Volgende',
    'eventpage.sort.recent': 'Nieuwste',
    'eventpage.sort.oldest': 'Oudste',
    'eventpage.upcomingBadge': 'Aankomend',
    'eventpage.heroTitle': 'Events & Hackathons',
    'eventpage.type.hackathon': 'Hackathon',
    'eventpage.type.workshop': 'Workshop',
    'eventpage.type.conference': 'Conference',
    'eventpage.type.meetup': 'Meetup',
    'eventpage.video': 'Video',
    // Default learned items
    'eventpage.learned.hackathon.1': 'Samenwerken onder tijdsdruk',
    'eventpage.learned.hackathon.2': 'Snel prototypen en itereren',
    'eventpage.learned.hackathon.3': 'Presenteren aan jury',
    'eventpage.learned.hackathon.4': 'Creatief problemen oplossen',
    'eventpage.learned.workshop.1': 'Hands-on ervaring opdoen',
    'eventpage.learned.workshop.2': 'Leren van experts',
    'eventpage.learned.workshop.3': 'Netwerken met vakgenoten',
    'eventpage.learned.workshop.4': 'Nieuwe tools ontdekken',
    'eventpage.learned.conference.1': 'Inzichten van sprekers',
    'eventpage.learned.conference.2': 'Industrie trends',
    'eventpage.learned.conference.3': 'Best practices',
    'eventpage.learned.conference.4': 'Professioneel netwerk uitbreiden',
    'eventpage.learned.meetup.1': 'Connecties leggen',
    'eventpage.learned.meetup.2': 'Kennis delen',
    'eventpage.learned.meetup.3': 'Inspiratie opdoen',
    'eventpage.learned.meetup.4': 'Community building',

    // Event 1: AI Fixathon Amsterdam
    'event.1.title': 'AI Fixathon Amsterdam',
    'event.1.displayDate': '13-14 December 2025',
    'event.1.location': 'Vandebron, Amsterdam',
    'event.1.participants': 'Max 40 deelnemers',
    'event.1.description': 'Een 2-daagse Fixathon waarbij we AI inzetten voor maatschappelijke impact. Met WorkRight Navigator ontwikkelden we een AI-concept dat kwetsbare werknemers na ontslag helpt.',
    'event.1.myExperience': 'Ik was bij de AI Fixathon Amsterdam samen met Hicham Tahiri, Rachid Ouaalit, Mohammad Falaha en Elfarouq Bakr. We werden opgesplitst in 2 teams en ik werkte samen met Damian en Elfarouq aan de WorkRight case. WorkRight Navigator is een AI-concept dat kwetsbare werknemers na ontslag helpt om beter te begrijpen welke stappen er zijn, wat er gebeurt, en hoe zij zich kunnen voorbereiden voordat ze met een juridisch loket of adviseur spreken. Het was een geweldige sfeer waar ik veel slimme en interessante mensen heb ontmoet en nieuwe tools leerde kennen zoals GreenPT en ActivePieces.',
    'event.1.highlight.1': '2-daagse Fixathon van zaterdag 10:00 tot zondag 18:00',
    'event.1.highlight.2': 'Ontwikkeling van WorkRight Navigator: AI-hulp voor kwetsbare werknemers na ontslag',
    'event.1.highlight.3': 'SDG focus op Gezondheid & Welzijn - werknemersrechten en juridische toegang',
    'event.1.highlight.4': 'Team van 3 personen: Damian Willemse, Elfarouq Bakr en mijzelf',
    'event.1.highlight.5': 'Introductie tot GreenPT voor duurzame LLM-implementatie',
    'event.1.highlight.6': 'Hands-on ervaring met ActivePieces voor low-code AI agent building',
    'event.1.highlight.7': 'Eten & drinken verzorgd door Vandebron gedurende de 2 dagen',
    'event.1.highlight.8': 'Geweldige sfeer met slimme en interessante mensen uit de AI-community',
    'event.1.highlight.9': 'Netwerken met builders gefocust op maatschappelijke impact en SDGs',
    'event.1.learned.1': 'AI-ontwikkeling gericht op maatschappelijke impact en werknemersrechten',
    'event.1.learned.2': 'GreenPT voor duurzame en energie-efficiënte LLM-implementatie',
    'event.1.learned.3': 'ActivePieces voor low-code AI agent building en workflow automatisering',
    'event.1.learned.4': 'Begrip van juridische processen en ondersteuning voor kwetsbare werknemers',
    'event.1.learned.5': 'Ontwerpen van toegankelijke AI-tools voor niet-technische gebruikers',
    'event.1.learned.6': 'Samenwerken aan maatschappelijke projecten binnen SDG-framework',
    'event.1.learned.7': 'Open-source ontwikkelpraktijken voor sociale tools',
    'event.1.learned.8': '2-daagse Fixathon uithoudingsvermogen en timemanagement',
    'event.1.conclusion': 'De AI Fixathon Amsterdam was een waardevolle ervaring waar we AI konden inzetten voor een echt maatschappelijk probleem. Met WorkRight Navigator ontwikkelden we een concept dat kwetsbare werknemers kan helpen bij het navigeren van complexe juridische processen na ontslag. Het was bijzonder leerzaam om te werken met nieuwe tools zoals GreenPT voor duurzame AI en ActivePieces voor low-code ontwikkeling. De geweldige sfeer en het netwerken met slimme mensen uit de AI-community maakte deze 2-daagse Fixathon een onvergetelijke ervaring.',

    // Event 2: Apify Challenge
    'event.2.title': 'Apify $1M Challenge: Amsterdam',
    'event.2.displayDate': '6 December 2025',
    'event.2.location': 'Meet Berlage, Amsterdam',
    'event.2.participants': '13 deelnemers',
    'event.2.description': 'In één dag met een team van 4 bouwden we een compleet woningscraping-platform. WoningSpotters verzamelt automatisch huur- en koopaanbod van Nederlandse woningsites.',
    'event.2.myExperience': 'Op 6 december gingen we met z\'n vieren de Apify $1M Challenge aan. Het resultaat: WoningSpotters – een platform dat woningdata verzamelt van vrijwel alle Nederlandse woningsites. We combineerden een React-frontend met Python en Apify voor scraping. Een dag vol gas geven, en het werkte!',
    'event.2.highlight.1': 'Eendaagse codeersessie (10:00-18:00) in het monumentale Meet Berlage',
    'event.2.highlight.2': 'Ontwikkeld WoningSpotters: automatische woningaanbod verzameling',
    'event.2.highlight.3': 'Brons gewonnen met ons team van vier!',
    'event.2.highlight.4': 'Tech stack: React UI + Python backend + Apify scrapers',
    'event.2.highlight.5': 'Diverse Nederlandse woningplatforms gekoppeld',
    'event.2.highlight.6': 'Directe hulp van Apify-ontwikkelaars ter plaatse',
    'event.2.highlight.7': 'Catering verzorgd gedurende de dag',
    'event.2.highlight.8': 'Contact gemaakt met andere scraping-enthousiastelingen',
    'event.2.learned.1': 'Scrapen van sites met diverse HTML-structuren',
    'event.2.learned.2': 'Apify gebruiken voor betrouwbare en schaalbare dataverzameling',
    'event.2.learned.3': 'Data transformeren en verwerken met Python-scripts',
    'event.2.learned.4': 'Snel interfaces bouwen met React',
    'event.2.learned.5': 'Van nul naar werkend product in één dag',
    'event.2.learned.6': 'Technische demo\'s geven aan de jury',
    'event.2.learned.7': 'Connecties maken in de scraping-wereld',
    'event.2.conclusion': 'Eén dag, één doel: WoningSpotters bouwen. Het lukte, inclusief een derde plaats als beloning. React, Python en Apify bleken een winnende combinatie voor dit woningmarkt-vraagstuk.',

    // Event 3: Build Weekend
    'event.3.title': 'Build Weekend by Young Creators & n8n',
    'event.3.displayDate': '29-30 November 2025',
    'event.3.location': 'StartDock, Amsterdam',
    'event.3.participants': '~150 builders (25 teams van 4-6 personen)',
    'event.3.description': 'Twee dagen non-stop bouwen met andere jonge developers. Met het team een werkend prototype opgeleverd onder begeleiding van ervaren mentors.',
    'event.3.myExperience': 'Samen met Damian Willemse, Mohammad Falaha, Rachid Ouaalit en Hicham Tahiri gingen we naar dit hackathon-weekend. Ons eindresultaat: FoodSwipe – een swipe-gebaseerde app voor het ontdekken van restaurants en recepten, TikTok-style. De AI-component liet gebruikers ingrediënten invoeren om direct een passend recept te krijgen.',
    'event.3.highlight.1': 'FoodSwipe gebouwd: restaurants en recepten ontdekken door te swipen',
    'event.3.highlight.2': 'AI-receptgenerator op basis van beschikbare ingrediënten',
    'event.3.highlight.3': 'Toolkit: n8n, Apify, Lovable, OpenAI en ElevenLabs',
    'event.3.highlight.4': 'Partners boden tools en ondersteuning',
    'event.3.highlight.5': 'Prijs gewonnen: 1 jaar n8n Cloud Pro (door een n8n-pet te dragen!)',
    'event.3.highlight.6': '48 uur intensief coderen en itereren als team',
    'event.3.learned.1': 'Processen automatiseren via n8n-workflows',
    'event.3.learned.2': 'Restaurant-info scrapen met Apify-actors',
    'event.3.learned.3': 'Snel prototypen met Lovable',
    'event.3.learned.4': 'OpenAI koppelen voor slimme receptsuggesties',
    'event.3.learned.5': 'Audio genereren via ElevenLabs voor promotionele content',
    'event.3.learned.6': 'Van idee naar demo-klaar product in 48 uur',
    'event.3.conclusion': 'Build Weekend was uitdagend maar ontzettend leerzaam. FoodSwipe werd een succes, ook zonder de hoofdprijs. De diepgaande kennismaking met n8n en Apify was de grootste winst. Bonus: door simpelweg een n8n-pet te dragen, scoorden we een jaar gratis Cloud Pro. Van schets naar werkend prototype in twee dagen – dat blijft bijzonder.',
    'event.3.cta.title': 'FoodSwipe op je radar?',
    'event.3.cta.text': 'Wil je als eerste weten wanneer FoodSwipe live gaat? Zet jezelf op de wachtlijst en we houden je op de hoogte!',
    'event.3.cta.buttonText': 'Zet me op de wachtlijst',

    // Event 4: Mendix CTF
    'event.4.title': 'Mendix Capture The Flag 2025',
    'event.4.displayDate': '9-10 Oktober 2025',
    'event.4.location': 'Wereldwijd (17 locaties)',
    'event.4.participants': '1.092 hackers wereldwijd',
    'event.4.description': 'Internationale hackcompetitie georganiseerd door Mendix. Twee dagen lang security-challenges kraken samen met hackers van over de hele wereld.',
    'event.4.myExperience': 'Mijn CTF-debuut, samen met Hicham Tahiri, Damian Willemse en Mohammad Falaha. De competitie had 27 challenges verdeeld over drie niveaus. Als complete beginners wisten we 12 flags te bemachtigen – meer dan we verwacht hadden.',
    'event.4.highlight.1': '27 security-puzzels over drie moeilijkheidsniveaus',
    'event.4.highlight.2': '12 flags gescoord als team',
    'event.4.highlight.3': '15+ workshops specifiek over Mendix-beveiliging',
    'event.4.highlight.4': 'Wereldwijd event: 1.092 hackers verspreid over 17 landen',
    'event.4.highlight.5': 'Coaching van security-specialisten ter plaatse',
    'event.4.highlight.6': 'Exclusieve swag voor alle deelnemers',
    'event.4.learned.1': 'Kennismaking met CTF-competities en ethische hackpraktijken',
    'event.4.learned.2': 'Kwetsbaarheden spotten binnen Mendix-applicaties',
    'event.4.learned.3': 'Begrijpen hoe aanvallen werken en hoe je ze tegengaat',
    'event.4.learned.4': 'Presteren als team onder hoge druk',
    'event.4.learned.5': 'Hands-on werken met pentest-tools',
    'event.4.conclusion': 'Maakte mijn debuut in de CTF-wereld en bemachtigde direct 12 van de 27 flags. Je leert hacken door te doen – bugs vinden en exploiteren in een veilige omgeving. De combinatie van competitie, begeleiding en een wereldwijde community maakte dit onvergetelijk.',

    // Event 5: CityLab010
    'event.5.title': 'CityLab010 Netwerkavond',
    'event.5.displayDate': '10 September 2025',
    'event.5.location': 'Het Timmerhuis, Rotterdam',
    'event.5.participants': 'TBD',
    'event.5.description': 'Netwerkavond van CityLab010: planmakers, ondernemers en gemeentemedewerkers ontmoeten elkaar om projecten te bespreken en feedback uit te wisselen.',
    'event.5.myExperience': 'Hicham Tahiri, Damian Willemse en ik presenteerden ons idee: een toerisme-app gericht op Rotterdam. Vanaf onze eigen tafel konden we pitchen aan voorbijgangers. De avond draaide om uitwisseling – we hoorden plannen van anderen en kregen waardevolle feedback op onze eigen visie.',
    'event.5.highlight.1': 'Stand om ons Rotterdam toerisme-concept te presenteren',
    'event.5.highlight.2': 'Face-to-face met de Stadsjury, andere planmakers en gemeente-experts',
    'event.5.highlight.3': 'Workshop over hoe het CityLab-programma in de praktijk werkt',
    'event.5.highlight.4': 'Concrete Blossom gaf een sessie over ondernemen vanuit je eigen leefwereld',
    'event.5.highlight.5': 'Inzichten over cultureel erfgoed als basis voor sociaal ondernemerschap',
    'event.5.highlight.6': 'Verhalen van alumni die het CityLab010-programma doorliepen',
    'event.5.learned.1': 'Hoe het CityLab010 ondersteuningsprogramma eruitziet voor starters',
    'event.5.learned.2': 'Ondernemen vanuit je persoonlijke context',
    'event.5.learned.3': 'Slim navigeren binnen gemeentelijke systemen en mogelijkheden',
    'event.5.learned.4': 'De link tussen erfgoed en sociaal ondernemerschap',
    'event.5.learned.5': 'Netwerken en feedback verzamelen van relevante stakeholders',
    'event.5.learned.6': 'Waar de Stadsjury op let bij het beoordelen van initiatieven',
    'event.5.conclusion': 'Een avond vol gesprekken die ons toerisme-idee aanscherpten. Contact met experts en andere planmakers bracht concrete verbeterpunten aan het licht en verduidelijkte wat de gemeente kan bieden. De workshops over leefwerelden en het CityLab-programma leverden praktisch toepasbare kennis op.',

    // Event 6: Computational Science
    'event.6.title': 'Hackathon Computational Science',
    'event.6.displayDate': '14 Juni 2025',
    'event.6.location': 'De Zalen van Zeven, Utrecht, Nederland',
    'event.6.participants': '~35 deelnemers (7 teams)',
    'event.6.description': 'Inaugurele wetenschappelijke hackathon: een watersimulatie-model programmeren in Julia voor Deltares.',
    'event.6.myExperience': 'Team BBBs: Damian Willemse, Hicham Tahiri en ik. De uitdaging: een 1D shallow-water solver schrijven in Julia, een taal waar we nul ervaring mee hadden. Zes uur lang worstelden we met numerieke modellen en visualisaties. Verwachtingen waren laag, het resultaat verraste: Eervolle Vermelding!',
    'event.6.highlight.1': 'Waterstroming gesimuleerd via 1D shallow-water vergelijkingen in Julia',
    'event.6.highlight.2': 'Locatie: De Zalen van Zeven, een oude kerk omgebouwd tot evenementenlocatie',
    'event.6.highlight.3': 'Demo gegeven aan specialisten van Deltares, VORtech BV en externe juryleden',
    'event.6.highlight.4': 'Eervolle Vermelding verdiend als Team BBBs',
    'event.6.highlight.5': 'Nieuwe contacten binnen de Nederlandse computational science-scene',
    'event.6.learned.1': 'Julia en numerieke simulatietechnieken voor het eerst toegepast',
    'event.6.learned.2': 'Shallow-water vergelijkingen vertalen naar watermodellen',
    'event.6.learned.3': 'Functioneren met een compleet onbekende tech stack onder tijdsdruk',
    'event.6.learned.4': 'Complexe technische ideeën bondig presenteren',
    'event.6.learned.5': 'Doorzetten ook wanneer het eindresultaat onzeker voelt',
    'event.6.conclusion': 'Zonder Julia-achtergrond toch een Eervolle Vermelding verdiend. Bewijs dat teamwork en doorzettingsvermogen belangrijker zijn dan voorkennis bij technische uitdagingen.',

    // Event 7: Xebia Hackathon
    'event.7.title': 'Xebia GitHub Copilot Hackathon',
    'event.7.displayDate': '21 Mei 2025',
    'event.7.location': 'Xebia Hilversum, Laapersveld 27, Nederland',
    'event.7.participants': '~50 deelnemers',
    'event.7.description': 'Hackathon rondom AI-gedreven programmeren. Leerde hoe je GitHub Copilot effectief inzet via speelse challenges.',
    'event.7.myExperience': 'Samen met Hicham Tahiri, Damian Willemse en Adel Atzouza kozen we voor Track 2: Advanced Mode. Thijs Limmen en Liuba Gonta gaven ons een intro. In twee uur bouwden we een werkend spel via AI-prompting – leerzaam en vermakelijk.',
    'event.7.highlight.1': 'Track 2 (Advanced Mode) introductie door Thijs Limmen en Liuba Gonta',
    'event.7.highlight.2': 'Twee uur om een game te bouwen via AI-prompting',
    'event.7.highlight.3': 'Een 2D shooter game gebouwd met Adel waar je elkaar moet neerschieten',
    'event.7.highlight.4': 'Direct hands-on met geavanceerde Copilot-functies',
    'event.7.highlight.5': 'Afsluiting met borrel waar iedereen zijn creaties liet zien',
    'event.7.learned.1': 'Prompts formuleren die complexere code genereren',
    'event.7.learned.2': 'Copilot toepassen voor game-logica en -ontwikkeling',
    'event.7.learned.3': 'Teamwork waarbij AI-tools de hoofdrol spelen',
    'event.7.learned.4': 'Repetitieve taken slim uitbesteden aan Copilot',
    'event.7.learned.5': 'Geavanceerde Copilot-functies die je workflow versnellen',
    'event.7.conclusion': 'Deze hackathon liet zien wat GitHub Copilot kan wanneer je de tool goed kent. Een 2D shooter game bouwen in twee uur was uitdagend maar waardevol. De inzichten over AI-prompting en het optimaal benutten van Copilot neem ik mee in mijn dagelijks werk.',

    // Event 8: Agency at Night
    'event.8.title': 'Agency at Night',
    'event.8.displayDate': '16 Mei 2025',
    'event.8.location': 'Rotterdam (51 bureaus)',
    'event.8.participants': 'TBD',
    'event.8.description': 'Speciale avond waarbij 51 Rotterdamse bureaus hun deuren openden. Inzichten opgedaan over marketing, design en digitale innovatie via presentaties en workshops.',
    'event.8.myExperience': 'Met Hicham Tahiri en Damian Willemse bezochten we zes bureaus en volgden diverse workshops. Een avond vol inspiratie over marketingautomatisering, AI-toepassingen, SEO-strategieën en creatieve uitdagingen.',
    'event.8.highlight.1': '100procent | united playground: sessie over marketingautomatisering en resultaatoptimalisatie',
    'event.8.highlight.2': 'Marketing Engineers: GeoGuessr-competitie',
    'event.8.highlight.3': 'Tastylemon: professionele fotoshoot en merkervaring',
    'event.8.highlight.4': 'Das Buro: branding-quiz met Das Buro Branding Professional Degree-certificaat',
    'event.8.highlight.5': 'Candid: challenge rond AI-prompting met v0.dev',
    'event.8.highlight.6': 'Buro voor de boeg: workshop over AI-gedreven zoekmachineoptimalisatie',
    'event.8.learned.1': 'Automatiseringsaanpak voor maximaal marketingresultaat',
    'event.8.learned.2': 'AI praktisch inzetten voor betere SEO-prestaties',
    'event.8.learned.3': 'Snel prototypes maken via v0.dev-prompting',
    'event.8.learned.4': 'Branding-basics plus officieel certificaat',
    'event.8.learned.5': 'Contacten leggen met creatieve professionals in Rotterdam',
    'event.8.learned.6': 'Beter begrip van verschillende bureau-disciplines en werkwijzen',
    'event.8.conclusion': 'Agency at Night bood een kijkje in diverse Rotterdamse creatieve bureaus in één avond. Van automatisering tot AI-SEO, van branding tot prompting – de variëteit aan sessies gaf een breed beeld van de creatieve sector. Het Das Buro Branding Professional Degree-certificaat was een mooie bonus.',

    // Error Fallback
    'error.title': 'Er ging iets mis',
    'error.message': 'Er is een fout opgetreden bij het laden van de pagina.',
    'error.retry': 'Probeer opnieuw',

    // BentoHero Section
    'bentohero.title': 'Over Mij',
    'bentohero.subtitle': 'Ontdek mijn verhaal, passies en expertise',
    'bentohero.student.title': 'Student',
    'bentohero.student.description': 'Mijn academische journey van MAVO tot HBO',
    'bentohero.student.meta': '2017 - 2027',
    'bentohero.business.title': 'Bedrijf',
    'bentohero.business.description': 'Entrepreneurial ventures & startups',
    'bentohero.business.meta': 'Startup Journey',
    'bentohero.work.title': 'Werk',
    'bentohero.work.description': 'Professionele rollen & prestaties',
    'bentohero.work.meta': '5+ Rollen',
    'bentohero.life.title': 'Persoonlijk',
    'bentohero.life.description': 'Hobbies, passies & wie ik ben',
    'bentohero.life.meta': 'Passies & Meer',

    // EventPage Categories
    'eventpage.category.cybersecurity': 'Cybersecurity',
    'eventpage.category.ai': 'AI & ML',
    'eventpage.category.blockchain': 'Blockchain',
    'eventpage.category.other': 'Overig',

    // Project Detail Page
    'projectdetail.notfound': 'Project niet gevonden',
    'projectdetail.backto': 'Terug naar Portfolio',
    'projectdetail.challenge.title': 'De Uitdaging & Oplossing',
    'projectdetail.problem': 'Het Probleem',
    'projectdetail.solution': 'De Oplossing',
    'projectdetail.features': 'Belangrijkste Features',
    'projectdetail.techstack': 'Technologie Stack',
    'projectdetail.frontend': 'Frontend',
    'projectdetail.backend': 'Backend',
    'projectdetail.architecture.title': 'Architectuur',
    'projectdetail.architecture.section': 'Systeem Architectuur',
    'projectdetail.challenges.title': 'Uitdagingen & Leerpunten',
    'projectdetail.challenges': 'Belangrijkste Uitdagingen',
    'projectdetail.learnings': 'Wat Ik Geleerd Heb',
    'projectdetail.github': 'Bekijk op GitHub',
    'projectdetail.demo': 'Live Demo',
    'projectdetail.more': 'Ontdek Meer Projecten',
    'projectdetail.viewall': 'Bekijk Alle Projecten',
  },
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.about': 'About Me',
    'nav.portfolio': 'Portfolio',
    'nav.events': 'Events',
    'nav.article': 'Articles',

    // Hero Section
    'hero.welcome': 'Welcome to my',
    'hero.portfolio': 'digital portfolio',
    'hero.role1': 'Full Stack Developer',
    'hero.role2': 'UI/UX Enthusiast',
    'hero.role3': 'Cybersecurity Enthusiast',
    'hero.description1': 'I transform ideas into',
    'hero.description1.highlight': 'digital reality',
    'hero.description2': 'As an IT student and passionate developer, I build modern web applications that are not only beautiful, but also',
    'hero.description2.highlight': 'innovative and user-friendly',
    'hero.description3': 'Specialized in React, TypeScript, Node.js and modern web technologies.',
    'hero.downloadCV': 'Download CV',
    'hero.follow': 'Find me on:',

    // About Section
    'about.title': 'About Me',
    'about.subtitle': 'With a passion for technology and innovation, I develop modern web applications that perfectly combine user experience and functionality.',
    'about.frontend': 'Frontend Development',
    'about.frontend.desc': 'React, TypeScript, Next.js, Tailwind CSS',
    'about.backend': 'Backend Development',
    'about.backend.desc': 'Node.js, Python, Databases, API Design',
    'about.uiux': 'UI/UX Design',
    'about.uiux.desc': 'Figma, Prototyping, User Research, Design Systems',
    'about.projects': 'Projects',
    'about.projects.desc': 'Discover my innovative projects from e-commerce platforms to portfolio dashboards.',
    'about.experience': 'Experience',
    'about.experience.desc': 'Years of experience building scalable web applications with modern technologies.',
    'about.passion': 'Passion',
    'about.passion.desc': 'Driven by perfection and always looking for new challenges in the digital world.',
    'about.tech': 'Technologies & Tools',

    // Skills Section
    'skills.title': 'My Skills',
    'skills.subtitle': 'An overview of my technical skills and expertise in various areas of software development.',
    'skills.learning.title': 'Always Learning & Growing',
    'skills.learning.desc': 'Technology is constantly evolving, and so am I. I am always learning new frameworks, tools and best practices to stay ahead in the world of web development.',

    // Portfolio Section
    'portfolio.title': 'My Portfolio',
    'portfolio.subtitle': 'A selection of my most recent and innovative projects that combine modern technologies and creative solutions.',
    'portfolio.featured': 'Featured Projects',
    'portfolio.other': 'Other Projects',
    'portfolio.keyFeatures': 'Key Features:',
    'portfolio.viewProject': 'View Project',
    'portfolio.cta.title': 'Interested in collaboration?',
    'portfolio.cta.subtitle': "Let's build something amazing together. Contact me for more information about my projects.",
    'portfolio.cta.button': 'View All Projects',

    // Contact Section
    'contact.title': "Let's work together",
    'contact.subtitle': 'Have an interesting project, a question about my work, or just want to chat? I would love to hear from you and am always open to new challenges!',
    'contact.form.title': 'Send a message',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.info': 'Contact Information',
    'contact.email': 'Email',
    'contact.email.desc': 'For projects and collaboration',
    'contact.linkedin': 'LinkedIn',
    'contact.linkedin.desc': 'Professional network',
    'contact.github': 'GitHub',
    'contact.github.desc': 'View my code',
    'contact.availability': 'Availability',
    'contact.available': 'Available for new projects',
    'contact.available.desc': 'I usually respond within 24 hours and am always interested in challenging projects.',
    'contact.expect': 'What can you expect?',
    'contact.expect1': 'Fast and professional response',
    'contact.expect2': 'Transparent communication about project scope',
    'contact.expect3': 'High quality code and design',
    'contact.expect4': 'Support after delivery',
    'contact.cta.title': 'Ready to bring your idea to life?',
    'contact.cta.subtitle': 'From concept to realization - let\'s build something amazing together that makes an impact.',
    'contact.cta.start': 'Start a Project',
    'contact.cta.portfolio': 'View Portfolio',

    // Footer Section
    'footer.description': 'Full-stack developer & UI/UX designer with a passion for building innovative digital solutions.',
    'footer.quickLinks': 'Quick Links',
    'footer.technologies': 'Technologies',
    'footer.services': 'Services',
    'footer.specialties': 'Specialties',
    'footer.services.web': 'Web Development',
    'footer.services.uiux': 'UI/UX Design',
    'footer.services.app': 'App Development',
    'footer.services.consulting': 'Consulting',
    'footer.spec.webapps': 'Web Apps',
    'footer.spec.uiux': 'UI/UX Design',
    'footer.spec.fullstack': 'Frontend & Backend',
    'footer.spec.databases': 'Databases',
    'footer.spec.apis': 'API\'s',
    'footer.spec.webapplications': 'Web Applications',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.copyright': '© 2025 Wishant Bhajan. All rights reserved.',

    // AboutMe Section (Homepage)
    'aboutme.intro1': 'Hi! I\'m Wishant, a passionate full-stack developer building modern, innovative web applications. With expertise in React, TypeScript and Node.js, I bring ideas to life.',
    'aboutme.intro2': 'From concept to deployment - I develop complete solutions with an eye for design, performance and user experience.',
    'aboutme.frontend.title': 'Frontend',
    'aboutme.frontend.text': 'React, TypeScript, Next.js',
    'aboutme.backend.title': 'Backend',
    'aboutme.backend.text': 'Node.js, Express, PostgreSQL',
    'aboutme.uiux.title': 'UI/UX Design',
    'aboutme.uiux.text': 'Figma, Tailwind, Responsive Design',
    'aboutme.readMore': 'Read more about me',

    // Contact Section (Homepage)
    'contact.connect': 'Let\'s Connect',
    'contact.intro': 'Open for new projects and collaborations. Feel free to contact me for a conversation about your next digital solution.',
    'contact.phone': 'Phone',
    'contact.availability.status': 'Available for freelance projects',

    // Portfolio Section (Homepage)
    'portfolio.header': 'Featured Projects',
    'portfolio.description': 'Cutting-edge solutions with modern technologies and innovative designs',
    'portfolio.filter.all': 'All Projects',
    'portfolio.filter.web': 'Web Apps',
    'portfolio.filter.ai': 'AI/ML',
    'portfolio.filter.blockchain': 'Blockchain',
    'portfolio.filter.data': 'Data Viz',
    'portfolio.status.live': 'LIVE',
    'portfolio.status.development': 'DEVELOPMENT',
    'portfolio.status.completed': 'COMPLETED',
    'portfolio.demo': 'Live Demo',
    'portfolio.github.link': 'GitHub',
    'portfolio.techTooltip': 'Click to filter',
    'portfolio.moretech': 'more',
    'portfolio.cta.header': 'Interested in collaboration?',
    'portfolio.cta.description': 'Let\'s build something amazing together. Contact me for projects, collaborations or just a chat about technology.',
    'portfolio.homepage.cta.button': 'Start a Project',

    // Project Data
    'project1.title': 'E-commerce Platform',
    'project1.desc': 'Modern webshop with AI-powered recommendations',
    'project1.extDesc': 'A fully functional webshop with React, Node.js and Stripe integration. Includes user management, product catalog, shopping cart and secure payments.',
    'project1.feature1': 'Responsive Design',
    'project1.feature2': 'Payment Integration',
    'project1.feature3': 'User Authentication',
    'project1.feature4': 'Admin Dashboard',
    'project2.title': 'AI Dashboard',
    'project2.desc': 'Real-time analytics with machine learning',
    'project2.extDesc': 'Interactive dashboard for portfolio management with real-time data visualization, analytics and content management system.',
    'project2.feature1': 'Real-time Analytics',
    'project2.feature2': 'Content Management',
    'project2.feature3': 'Data Visualization',
    'project2.feature4': 'Multi-user Support',
    'project3.title': 'Blockchain Wallet',
    'project3.desc': 'Secure crypto wallet with multi-chain support',
    'project3.feature1': 'Multi-chain',
    'project3.feature2': 'Hardware Wallet',
    'project3.feature3': 'DeFi Integration',
    'project4.title': 'Task Management',
    'project4.desc': 'Productivity app with AI assistant',
    'project4.feature1': 'Drag & Drop',
    'project4.feature2': 'Team Collaboration',
    'project4.feature3': 'AI Suggestions',
    'project5.title': 'Weather Dashboard',
    'project5.desc': 'Real-time weather with predictive analytics',
    'project5.feature1': 'Interactive Maps',
    'project5.feature2': 'Forecasting',
    'project5.feature3': 'Alerts',
    'project6.title': 'Social Platform',
    'project6.desc': 'Next-gen social media with privacy focus',
    'project6.feature1': 'End-to-end Encryption',
    'project6.feature2': 'Live Chat',
    'project6.feature3': 'Stories',

    // Skills Categories
    'skills.category.frontend': 'Frontend Development',
    'skills.category.backend': 'Backend Development',
    'skills.category.tools': 'Tools & Technologies',
    'skills.category.languages': 'Programming Languages',

    // ContactPage
    'contactpage.hero.title': 'Let\'s Connect',
    'contactpage.hero.subtitle': 'Have a project in mind? Let\'s build something amazing together.',
    'contactpage.form.title': 'Send a Message',
    'contactpage.form.name.label': 'Name',
    'contactpage.form.name.placeholder': 'John Doe',
    'contactpage.form.email.label': 'Email',
    'contactpage.form.email.placeholder': 'john@example.com',
    'contactpage.form.subject.label': 'Subject',
    'contactpage.form.subject.placeholder': 'Select a subject',
    'contactpage.form.subject.project': 'New Project',
    'contactpage.form.subject.collaboration': 'Collaboration',
    'contactpage.form.subject.consultation': 'Consultation',
    'contactpage.form.subject.other': 'Other',
    'contactpage.form.message.label': 'Message',
    'contactpage.form.message.placeholder': 'Tell me about your project...',
    'contactpage.form.submit': 'Send Message',
    'contactpage.form.sending': 'Sending...',
    'contactpage.form.success': 'Message sent successfully!',
    'contactpage.form.error': 'Something went wrong. Please try again.',
    'contactpage.info.title': 'Get in Touch',
    'contactpage.info.location': 'Location',
    'contactpage.info.netherlands': 'Netherlands',
    'contactpage.social.title': 'Connect on Social',
    'contactpage.social.twitter': 'Twitter',
    'contactpage.social.discord': 'Discord',
    'contactpage.availability.title': 'Currently Available',
    'contactpage.availability.desc': 'I\'m open for freelance projects and full-time opportunities. Response time: usually within 24 hours.',
    'contactpage.faq.title': 'Frequently Asked Questions',
    'contactpage.faq.subtitle': 'Answers to frequently asked questions',
    'contactpage.faq1.q': 'What services do you offer?',
    'contactpage.faq1.a': 'Full stack web development, UI/UX design, API development, security auditing, and technical consulting.',
    'contactpage.faq2.q': 'What is your typical project timeline?',
    'contactpage.faq2.a': 'Project timelines vary based on complexity. Small projects: 2-4 weeks, Medium: 1-3 months, Large: 3-6 months.',
    'contactpage.faq3.q': 'Do you work remotely?',
    'contactpage.faq3.a': 'Yes! I work with clients globally and am comfortable with remote collaboration tools and async communication.',
    'contactpage.faq4.q': 'What are your rates?',
    'contactpage.faq4.a': 'Rates depend on project scope and complexity. Contact me for a custom quote tailored to your needs.',

    // AboutPage
    'aboutpage.hero.title': 'About Me',
    'aboutpage.hero.subtitle': 'A passionate Full Stack Developer focused on cybersecurity, modern web technologies and creating innovative digital experiences.',
    'aboutpage.role.developer': 'Developer',
    'aboutpage.role.designer': 'Designer',
    'aboutpage.role.innovator': 'Innovator',
    'aboutpage.role.problemsolver': 'Problem Solver',
    'aboutpage.tab.journey': 'My Journey',
    'aboutpage.tab.expertise': 'Expertise',
    'aboutpage.tab.values': 'Values',
    'aboutpage.journey.2020.event': 'Started programming',
    'aboutpage.journey.2020.desc': 'First steps in web development',
    'aboutpage.journey.2021.event': 'Deep dive in React & TypeScript',
    'aboutpage.journey.2021.desc': 'Modern frontend frameworks',
    'aboutpage.journey.2022.event': 'Full Stack Development',
    'aboutpage.journey.2022.desc': 'Backend, databases and cloud',
    'aboutpage.journey.2023.event': 'Cybersecurity Focus',
    'aboutpage.journey.2023.desc': 'Secure coding practices',
    'aboutpage.journey.2024.event': 'UI/UX Specialist',
    'aboutpage.journey.2024.desc': 'Design systems and user experience',
    'aboutpage.expertise.frontend': 'Frontend Architecture',
    'aboutpage.expertise.backend': 'Backend Development',
    'aboutpage.expertise.cybersecurity': 'Cybersecurity',
    'aboutpage.expertise.uiux': 'UI/UX Design',
    'aboutpage.expertise.devops': 'DevOps & Cloud',
    'aboutpage.value.security.title': 'Security First',
    'aboutpage.value.security.desc': 'Every line of code with security in mind',
    'aboutpage.value.performance.title': 'Performance',
    'aboutpage.value.performance.desc': 'Fast, optimized applications',
    'aboutpage.value.ux.title': 'User Experience',
    'aboutpage.value.ux.desc': 'Intuitive and beautiful interfaces',
    'aboutpage.value.innovation.title': 'Innovation',
    'aboutpage.value.innovation.desc': 'Always looking for better solutions',
    'aboutpage.cta.title': 'Let\'s Build Together',
    'aboutpage.cta.subtitle': 'Looking for a developer who can realize your vision?',
    'aboutpage.cta.button': 'View Portfolio',

    // Featured Projects & Skills Section
    'featured.projects.title': 'Featured Projects',
    'featured.projects.description': 'Cutting-edge solutions with modern technologies',
    'featured.skills.title': 'Technical Skills',
    'featured.skills.description': 'Expertise in modern technologies and frameworks',
    'featured.viewAllProjects': 'View All Projects',

    // Project Cards - Real Projects
    'featured.wishshield.desc': 'Vulnerability scanner for OWASP Top 10 risks',
    'featured.tabletech.desc': 'Restaurant software for hospitality businesses',
    'featured.calendify.desc': 'Office calendar for hybrid workplaces',
    'featured.wishguard.desc': 'Security monitoring system',
    'featured.cryptobot.desc': 'Crypto trading bot with AI algorithms',
    'featured.urbanmobility.desc': 'Urban mobility solution',

    // Project Labels
    'featured.label.cybersecurity': 'Cybersecurity',
    'featured.label.live': 'Live',
    'featured.label.personal': 'Personal',
    'featured.label.comingSoon': 'Coming Soon',

    // Skills
    'featured.skill.ai': 'All Programming Languages',
    'featured.skill.ai.note': 'I know how to talk to AI',
    'featured.skill.react': 'React / Next.js',
    'featured.skill.typescript': 'TypeScript',
    'featured.skill.csharp': 'C#',
    'featured.skill.nodejs': 'Node.js',
    'featured.skill.python': 'Python',
    'featured.skill.cybersecurity': 'Cybersecurity',
    'featured.skill.cybersecurity.note': 'Actively developing',
    'featured.skill.databases': 'Databases',
    'featured.skill.docker': 'Docker / K8s',
    'featured.skill.ml': 'Machine Learning',
    'featured.skill.other': 'Other technologies',

    // Skill Categories
    'featured.category.ai': 'AI',
    'featured.category.frontend': 'Frontend',
    'featured.category.backend': 'Backend',
    'featured.category.security': 'Security',
    'featured.category.database': 'Database',
    'featured.category.devops': 'DevOps',
    'featured.category.tools': 'Tools',

    // Skill Stats
    'featured.stats.technologies': 'Technologies',
    'featured.stats.experience': 'Years Exp',
    'featured.stats.projects': 'Projects',

    // About Section (Homepage)
    'aboutsection.title': 'About Me',
    'aboutsection.subtitle': '3rd year Computer Science student with a passion for cybersecurity and innovative web solutions. I combine creativity with technical expertise to build secure and user-friendly applications.',
    'aboutsection.terminal.name': 'Name: Wishant Bhajan',
    'aboutsection.terminal.age': 'Age: 20',
    'aboutsection.terminal.location': 'Location: Rotterdam, NL',
    'aboutsection.terminal.role': 'Role: 3rd Year Computer Science Student',
    'aboutsection.terminal.status': 'Status: Available for work',
    'aboutsection.terminal.passion': 'Passion: Cybersecurity & Innovation',
    'aboutsection.terminal.experience': 'Experience: 3+ years',
    'aboutsection.button': 'More About Me',
    'aboutsection.profilecard.name': 'Wishant Bhajan',
    'aboutsection.profilecard.title': 'Software Engineer',
    'aboutsection.profilecard.status': 'Available for work',
    'aboutsection.profilecard.contact': 'Contact',

    // Portfolio Page
    'portfoliopage.title': 'My Portfolio',
    'portfoliopage.subtitle': 'Discover my projects and work',
    'portfoliopage.search': 'Search projects...',
    'portfoliopage.tier.all': 'All Tiers',
    'portfoliopage.tier.i': 'Tier I',
    'portfoliopage.tier.ii': 'Tier II',
    'portfoliopage.tier.iii': 'Tier III',
    'portfoliopage.subcategory.all': 'All',
    'portfoliopage.subcategory.websites': 'Websites',
    'portfoliopage.subcategory.crypto': 'Crypto',
    'portfoliopage.subcategory.systems': 'Systems',
    'portfoliopage.category.cybersecurity': 'Cybersecurity',
    'portfoliopage.category.bedrijven': 'Companies',
    'portfoliopage.category.persoonlijk': 'Personal',
    'portfoliopage.backToCategories': 'Back to Categories',
    'portfoliopage.projects': 'projects',
    'portfoliopage.project': 'project',
    'portfoliopage.noProjects': 'No projects in this category yet.',
    // Project Card
    'project.comingSoon': 'Coming Soon',
    'project.github': 'GitHub',
    'project.liveDemo': 'Live Demo',
    // Project Modal
    'project.modal.featuredProject': 'Featured Project',
    'project.modal.technologies': 'Technologies',
    'project.modal.viewOnGitHub': 'View on GitHub',
    'project.modal.viewLiveDemo': 'Live Demo',
    'project.modal.caseStudy': 'Case Study',
    'project.modal.close': 'Close',
    // Cybersecurity Modal
    'project.modal.cybersecurity.title': 'Coming Soon',
    'project.modal.cybersecurity.message': 'This project is completed, but is currently being processed for presentation.',
    'project.modal.cybersecurity.understood': 'Understood',
    // Pending Info Modal
    'project.modal.pending.message': 'This project is completed. Project information will be added to this page soon.',
    'project.modal.pending.viewWebsite': 'View the live website:',
    'project.modal.pending.understood': 'Understood',

    // Event/Calendify Page
    'eventpage.title': 'Events & Hackathons',
    'eventpage.subtitle': 'Discover my journey through various tech events, hackathons and workshops where I participated and learned new skills.',
    'eventpage.filter.all': 'All',
    'eventpage.filter.hackathon': 'Hackathon',
    'eventpage.filter.conference': 'Conference',
    'eventpage.filter.workshop': 'Workshop',
    'eventpage.filter.competition': 'Competition',
    'eventpage.modal.highlights': 'Highlights',
    'eventpage.modal.technologies': 'Technologies',
    'eventpage.modal.moreinfo': 'More Info',
    'eventpage.empty': 'No events found in this category.',
    'eventpage.cta.title': 'Want to join me at an event?',
    'eventpage.cta.subtitle': 'I\'m always looking for new hackathons and tech events to attend.',
    'eventpage.more': 'more',
    'eventpage.filter.cybersecurity': 'Cybersecurity',
    'eventpage.filter.ai': 'AI',
    'eventpage.filter.blockchain': 'Blockchain',
    'eventpage.filter.other': 'Other',
    'eventpage.myExperience': 'My Experience',
    'eventpage.myExpectations': 'My Expectations',
    'eventpage.upcomingEvent': 'Upcoming Event',
    'eventpage.allEvents': 'All events',
    'eventpage.aboutEvent': 'About this event',
    'eventpage.highlights': 'Highlights',
    'eventpage.photosVideos': 'Photos & Videos',
    'eventpage.photosVideosSoon': 'Photos & videos coming soon...',
    'eventpage.whatILearned': 'What I Learned',
    'eventpage.whatIWantToLearn': 'What I Want to Learn',
    'eventpage.conclusion': 'Conclusion',
    'eventpage.date': 'Date',
    'eventpage.location': 'Location',
    'eventpage.category': 'Category',
    'eventpage.participants': 'Participants',
    'eventpage.otherEvents': "Other events I've attended",
    'eventpage.viewDetails': 'View details',
    'eventpage.viewAllEvents': 'View all events',
    'eventpage.noEventsFound': 'No events found in this category',
    'eventpage.close': 'Close (Escape)',
    'eventpage.previous': 'Previous',
    'eventpage.next': 'Next',
    'eventpage.sort.recent': 'Recent',
    'eventpage.sort.oldest': 'Oldest',
    'eventpage.upcomingBadge': 'Upcoming',
    'eventpage.heroTitle': 'Events & Hackathons',
    'eventpage.type.hackathon': 'Hackathon',
    'eventpage.type.workshop': 'Workshop',
    'eventpage.type.conference': 'Conference',
    'eventpage.type.meetup': 'Meetup',
    'eventpage.video': 'Video',
    // Default learned items
    'eventpage.learned.hackathon.1': 'Collaborating under time pressure',
    'eventpage.learned.hackathon.2': 'Rapid prototyping and iterating',
    'eventpage.learned.hackathon.3': 'Presenting to jury',
    'eventpage.learned.hackathon.4': 'Creative problem solving',
    'eventpage.learned.workshop.1': 'Gaining hands-on experience',
    'eventpage.learned.workshop.2': 'Learning from experts',
    'eventpage.learned.workshop.3': 'Networking with peers',
    'eventpage.learned.workshop.4': 'Discovering new tools',
    'eventpage.learned.conference.1': 'Insights from speakers',
    'eventpage.learned.conference.2': 'Industry trends',
    'eventpage.learned.conference.3': 'Best practices',
    'eventpage.learned.conference.4': 'Expanding professional network',
    'eventpage.learned.meetup.1': 'Building connections',
    'eventpage.learned.meetup.2': 'Sharing knowledge',
    'eventpage.learned.meetup.3': 'Getting inspired',
    'eventpage.learned.meetup.4': 'Community building',

    // Event 1: AI Fixathon Amsterdam
    'event.1.title': 'AI Fixathon Amsterdam',
    'event.1.displayDate': 'December 13-14, 2025',
    'event.1.location': 'Vandebron, Amsterdam',
    'event.1.participants': 'Max 40 participants',
    'event.1.description': 'A 2-day Fixathon where we deployed AI for social impact. With WorkRight Navigator, we developed an AI concept that helps vulnerable employees after dismissal.',
    'event.1.myExperience': 'I attended the AI Fixathon Amsterdam together with Hicham Tahiri, Rachid Ouaalit, Mohammad Falaha and Elfarouq Bakr. We were split into 2 teams and I worked with Damian and Elfarouq on the WorkRight case. WorkRight Navigator is an AI concept that helps vulnerable employees after dismissal to better understand what steps are available, what happens, and how they can prepare before speaking with a legal desk or advisor. It was a great atmosphere where I met many smart and interesting people and learned about new tools like GreenPT and ActivePieces.',
    'event.1.highlight.1': '2-day Fixathon from Saturday 10:00 to Sunday 18:00',
    'event.1.highlight.2': 'Development of WorkRight Navigator: AI assistance for vulnerable employees after dismissal',
    'event.1.highlight.3': 'SDG focus on Health & Well-being - employee rights and legal access',
    'event.1.highlight.4': 'Team of 3 people: Damian Willemse, Elfarouq Bakr and myself',
    'event.1.highlight.5': 'Introduction to GreenPT for sustainable LLM implementation',
    'event.1.highlight.6': 'Hands-on experience with ActivePieces for low-code AI agent building',
    'event.1.highlight.7': 'Food & drinks provided by Vandebron throughout the 2 days',
    'event.1.highlight.8': 'Great atmosphere with smart and interesting people from the AI community',
    'event.1.highlight.9': 'Networking with builders focused on social impact and SDGs',
    'event.1.learned.1': 'AI development focused on social impact and employee rights',
    'event.1.learned.2': 'GreenPT for sustainable and energy-efficient LLM implementation',
    'event.1.learned.3': 'ActivePieces for low-code AI agent building and workflow automation',
    'event.1.learned.4': 'Understanding legal processes and support for vulnerable employees',
    'event.1.learned.5': 'Designing accessible AI tools for non-technical users',
    'event.1.learned.6': 'Collaborating on social impact projects within SDG framework',
    'event.1.learned.7': 'Open-source development practices for social tools',
    'event.1.learned.8': '2-day Fixathon stamina and time management',
    'event.1.conclusion': 'The AI Fixathon Amsterdam was a valuable experience where we could deploy AI for a real social problem. With WorkRight Navigator, we developed a concept that can help vulnerable employees navigate complex legal processes after dismissal. It was particularly educational to work with new tools like GreenPT for sustainable AI and ActivePieces for low-code development. The great atmosphere and networking with smart people from the AI community made this 2-day Fixathon a memorable experience.',

    // Event 2: Apify Challenge
    'event.2.title': 'Apify $1M Challenge: Amsterdam',
    'event.2.displayDate': 'December 6, 2025',
    'event.2.location': 'Meet Berlage, Amsterdam',
    'event.2.participants': '13 participants',
    'event.2.description': 'In one day with a team of 4, we built a complete housing scraping platform. WoningSpotters automatically collects rental and sale listings from Dutch real estate sites.',
    'event.2.myExperience': 'On December 6th, the four of us took on the Apify $1M Challenge. The result: WoningSpotters – a platform that collects housing data from virtually all Dutch housing sites. We combined a React frontend with Python and Apify for scraping. A day of full-throttle work, and it worked!',
    'event.2.highlight.1': 'One-day coding session (10:00-18:00) in the monumental Meet Berlage',
    'event.2.highlight.2': 'Developed WoningSpotters: automatic housing listing collection',
    'event.2.highlight.3': 'Won bronze with our team of four!',
    'event.2.highlight.4': 'Tech stack: React UI + Python backend + Apify scrapers',
    'event.2.highlight.5': 'Connected various Dutch housing platforms',
    'event.2.highlight.6': 'Direct help from Apify developers on-site',
    'event.2.highlight.7': 'Catering provided throughout the day',
    'event.2.highlight.8': 'Connected with other scraping enthusiasts',
    'event.2.learned.1': 'Scraping sites with diverse HTML structures',
    'event.2.learned.2': 'Using Apify for reliable and scalable data collection',
    'event.2.learned.3': 'Transforming and processing data with Python scripts',
    'event.2.learned.4': 'Quickly building interfaces with React',
    'event.2.learned.5': 'Going from zero to working product in one day',
    'event.2.learned.6': 'Giving technical demos to the jury',
    'event.2.learned.7': 'Making connections in the scraping world',
    'event.2.conclusion': 'One day, one goal: building WoningSpotters. We succeeded, including a third place as a reward. React, Python and Apify proved to be a winning combination for this housing market problem.',

    // Event 3: Build Weekend
    'event.3.title': 'Build Weekend by Young Creators & n8n',
    'event.3.displayDate': 'November 29-30, 2025',
    'event.3.location': 'StartDock, Amsterdam',
    'event.3.participants': '~150 builders (25 teams of 4-6 people)',
    'event.3.description': 'Two days of non-stop building with other young developers. Delivered a working prototype with the team under guidance of experienced mentors.',
    'event.3.myExperience': 'Together with Damian Willemse, Mohammad Falaha, Rachid Ouaalit and Hicham Tahiri, we headed to this hackathon weekend. Our end result: FoodSwipe – a swipe-based app for discovering restaurants and recipes, TikTok-style. The AI component let users enter ingredients to instantly get a matching recipe.',
    'event.3.highlight.1': 'Built FoodSwipe: discover restaurants and recipes through swiping',
    'event.3.highlight.2': 'AI recipe generator based on available ingredients',
    'event.3.highlight.3': 'Toolkit: n8n, Apify, Lovable, OpenAI and ElevenLabs',
    'event.3.highlight.4': 'Partners provided tools and support',
    'event.3.highlight.5': 'Won a prize: 1 year n8n Cloud Pro (by wearing an n8n cap!)',
    'event.3.highlight.6': '48 hours of intensive coding and iterating as a team',
    'event.3.learned.1': 'Automating processes via n8n workflows',
    'event.3.learned.2': 'Scraping restaurant info with Apify actors',
    'event.3.learned.3': 'Rapid prototyping with Lovable',
    'event.3.learned.4': 'Connecting OpenAI for smart recipe suggestions',
    'event.3.learned.5': 'Generating audio via ElevenLabs for promotional content',
    'event.3.learned.6': 'Going from idea to demo-ready product in 48 hours',
    'event.3.conclusion': 'Build Weekend was challenging but incredibly educational. FoodSwipe became a success, even without the main prize. The in-depth introduction to n8n and Apify was the biggest gain. Bonus: by simply wearing an n8n cap, we scored a year of free Cloud Pro. From sketch to working prototype in two days – that remains special.',
    'event.3.cta.title': 'FoodSwipe on your radar?',
    'event.3.cta.text': 'Want to be the first to know when FoodSwipe goes live? Put yourself on the waitlist and we\'ll keep you updated!',
    'event.3.cta.buttonText': 'Put me on the waitlist',

    // Event 4: Mendix CTF
    'event.4.title': 'Mendix Capture The Flag 2025',
    'event.4.displayDate': 'October 9-10, 2025',
    'event.4.location': 'Worldwide (17 locations)',
    'event.4.participants': '1,092 hackers worldwide',
    'event.4.description': 'International hacking competition organized by Mendix. Two days of cracking security challenges together with hackers from around the world.',
    'event.4.myExperience': 'My CTF debut, together with Hicham Tahiri, Damian Willemse and Mohammad Falaha. The competition had 27 challenges spread across three levels. As complete beginners, we managed to capture 12 flags – more than we expected.',
    'event.4.highlight.1': '27 security puzzles across three difficulty levels',
    'event.4.highlight.2': '12 flags scored as a team',
    'event.4.highlight.3': '15+ workshops specifically about Mendix security',
    'event.4.highlight.4': 'Global event: 1,092 hackers spread across 17 countries',
    'event.4.highlight.5': 'Coaching from security specialists on-site',
    'event.4.highlight.6': 'Exclusive swag for all participants',
    'event.4.learned.1': 'Introduction to CTF competitions and ethical hacking practices',
    'event.4.learned.2': 'Spotting vulnerabilities within Mendix applications',
    'event.4.learned.3': 'Understanding how attacks work and how to counter them',
    'event.4.learned.4': 'Performing as a team under high pressure',
    'event.4.learned.5': 'Hands-on work with pentest tools',
    'event.4.conclusion': 'Made my debut in the CTF world and immediately captured 12 out of 27 flags. You learn hacking by doing – finding and exploiting bugs in a safe environment. The combination of competition, guidance and a worldwide community made this unforgettable.',

    // Event 5: CityLab010
    'event.5.title': 'CityLab010 Network Event',
    'event.5.displayDate': 'September 10, 2025',
    'event.5.location': 'Het Timmerhuis, Rotterdam',
    'event.5.participants': 'TBD',
    'event.5.description': 'Networking evening by CityLab010: planmakers, entrepreneurs and municipality employees meet to discuss projects and exchange feedback.',
    'event.5.myExperience': 'Hicham Tahiri, Damian Willemse and I presented our idea: a tourism app focused on Rotterdam. From our own table, we could pitch to passersby. The evening was all about exchange – we heard others\' plans and received valuable feedback on our own vision.',
    'event.5.highlight.1': 'Stand to present our Rotterdam tourism concept',
    'event.5.highlight.2': 'Face-to-face with the City Jury, other planmakers and municipality experts',
    'event.5.highlight.3': 'Workshop on how the CityLab program works in practice',
    'event.5.highlight.4': 'Concrete Blossom gave a session on entrepreneurship from your own living world',
    'event.5.highlight.5': 'Insights on cultural heritage as a foundation for social entrepreneurship',
    'event.5.highlight.6': 'Stories from alumni who completed the CityLab010 program',
    'event.5.learned.1': 'How the CityLab010 support program looks for starters',
    'event.5.learned.2': 'Entrepreneurship starting from your personal context',
    'event.5.learned.3': 'Smart navigation within municipal systems and opportunities',
    'event.5.learned.4': 'The link between heritage and social entrepreneurship',
    'event.5.learned.5': 'Networking and collecting feedback from relevant stakeholders',
    'event.5.learned.6': 'What the City Jury looks for when evaluating initiatives',
    'event.5.conclusion': 'An evening full of conversations that sharpened our tourism idea. Contact with experts and other planmakers brought concrete improvement points to light and clarified what the municipality can offer. The workshops on living worlds and the CityLab program provided practically applicable knowledge.',

    // Event 6: Computational Science
    'event.6.title': 'Hackathon Computational Science',
    'event.6.displayDate': 'June 14, 2025',
    'event.6.location': 'De Zalen van Zeven, Utrecht, Netherlands',
    'event.6.participants': '~35 participants (7 teams)',
    'event.6.description': 'Inaugural scientific hackathon: programming a water simulation model in Julia for Deltares.',
    'event.6.myExperience': 'Team BBBs: Damian Willemse, Hicham Tahiri and me. The challenge: writing a 1D shallow-water solver in Julia, a language we had zero experience with. For six hours we wrestled with numerical models and visualizations. Expectations were low, the result surprised: Honorable Mention!',
    'event.6.highlight.1': 'Simulated water flow via 1D shallow-water equations in Julia',
    'event.6.highlight.2': 'Venue: De Zalen van Zeven, an old church converted into an event location',
    'event.6.highlight.3': 'Demo given to specialists from Deltares, VORtech BV and external judges',
    'event.6.highlight.4': 'Earned Honorable Mention as Team BBBs',
    'event.6.highlight.5': 'New contacts within the Dutch computational science scene',
    'event.6.learned.1': 'Applied Julia and numerical simulation techniques for the first time',
    'event.6.learned.2': 'Translating shallow-water equations into water models',
    'event.6.learned.3': 'Functioning with a completely unknown tech stack under time pressure',
    'event.6.learned.4': 'Presenting complex technical ideas concisely',
    'event.6.learned.5': 'Persevering even when the end result feels uncertain',
    'event.6.conclusion': 'Without Julia background, we still earned an Honorable Mention. Proof that teamwork and perseverance are more important than prior knowledge in technical challenges.',

    // Event 7: Xebia Hackathon
    'event.7.title': 'Xebia GitHub Copilot Hackathon',
    'event.7.displayDate': 'May 21, 2025',
    'event.7.location': 'Xebia Hilversum, Laapersveld 27, Netherlands',
    'event.7.participants': '~50 participants',
    'event.7.description': 'Hackathon around AI-driven programming. Learned how to effectively use GitHub Copilot through playful challenges.',
    'event.7.myExperience': 'Together with Hicham Tahiri, Damian Willemse and Adel Atzouza, we chose Track 2: Advanced Mode. Thijs Limmen and Liuba Gonta gave us an intro. In two hours, we built a working game through AI prompting – educational and entertaining.',
    'event.7.highlight.1': 'Track 2 (Advanced Mode) introduction by Thijs Limmen and Liuba Gonta',
    'event.7.highlight.2': 'Two hours to build a game via AI prompting',
    'event.7.highlight.3': 'Built a 2D shooter game with Adel where you have to shoot each other',
    'event.7.highlight.4': 'Immediately hands-on with advanced Copilot features',
    'event.7.highlight.5': 'Closing with drinks where everyone showed their creations',
    'event.7.learned.1': 'Formulating prompts that generate more complex code',
    'event.7.learned.2': 'Applying Copilot for game logic and development',
    'event.7.learned.3': 'Teamwork where AI tools play the main role',
    'event.7.learned.4': 'Smartly outsourcing repetitive tasks to Copilot',
    'event.7.learned.5': 'Advanced Copilot features that speed up your workflow',
    'event.7.conclusion': 'This hackathon showed what GitHub Copilot can do when you know the tool well. Building a 2D shooter game in two hours was challenging but valuable. The insights on AI prompting and optimally using Copilot I take with me in my daily work.',

    // Event 8: Agency at Night
    'event.8.title': 'Agency at Night',
    'event.8.displayDate': 'May 16, 2025',
    'event.8.location': 'Rotterdam (51 agencies)',
    'event.8.participants': 'TBD',
    'event.8.description': 'Special evening where 51 Rotterdam agencies opened their doors. Gained insights about marketing, design and digital innovation through presentations and workshops.',
    'event.8.myExperience': 'With Hicham Tahiri and Damian Willemse, we visited six agencies and attended various workshops. An evening full of inspiration about marketing automation, AI applications, SEO strategies and creative challenges.',
    'event.8.highlight.1': '100procent | united playground: session on marketing automation and result optimization',
    'event.8.highlight.2': 'Marketing Engineers: GeoGuessr competition',
    'event.8.highlight.3': 'Tastylemon: professional photoshoot and brand experience',
    'event.8.highlight.4': 'Das Buro: branding quiz with Das Buro Branding Professional Degree certificate',
    'event.8.highlight.5': 'Candid: challenge around AI prompting with v0.dev',
    'event.8.highlight.6': 'Buro voor de boeg: workshop on AI-driven search engine optimization',
    'event.8.learned.1': 'Automation approach for maximum marketing results',
    'event.8.learned.2': 'Practically deploying AI for better SEO performance',
    'event.8.learned.3': 'Creating quick prototypes via v0.dev prompting',
    'event.8.learned.4': 'Branding basics plus official certificate',
    'event.8.learned.5': 'Building contacts with creative professionals in Rotterdam',
    'event.8.learned.6': 'Better understanding of different agency disciplines and work styles',
    'event.8.conclusion': 'Agency at Night offered a glimpse into various Rotterdam creative agencies in one evening. From automation to AI-SEO, from branding to prompting – the variety of sessions provided a broad picture of the creative sector. The Das Buro Branding Professional Degree certificate was a nice bonus.',

    // Error Fallback
    'error.title': 'Something went wrong',
    'error.message': 'An error occurred while loading the page.',
    'error.retry': 'Try again',

    // BentoHero Section
    'bentohero.title': 'About Me',
    'bentohero.subtitle': 'Discover my story, passions and expertise',
    'bentohero.student.title': 'Student',
    'bentohero.student.description': 'My academic journey from MAVO to HBO',
    'bentohero.student.meta': '2017 - 2027',
    'bentohero.business.title': 'Business',
    'bentohero.business.description': 'Entrepreneurial ventures & startups',
    'bentohero.business.meta': 'Startup Journey',
    'bentohero.work.title': 'Work',
    'bentohero.work.description': 'Professional roles & achievements',
    'bentohero.work.meta': '5+ Roles',
    'bentohero.life.title': 'Personal',
    'bentohero.life.description': 'Hobbies, passions & who I am',
    'bentohero.life.meta': 'Passions & More',

    // EventPage Categories
    'eventpage.category.cybersecurity': 'Cybersecurity',
    'eventpage.category.ai': 'AI & ML',
    'eventpage.category.blockchain': 'Blockchain',
    'eventpage.category.other': 'Other',

    // Project Detail Page
    'projectdetail.notfound': 'Project not found',
    'projectdetail.backto': 'Back to Portfolio',
    'projectdetail.challenge.title': 'The Challenge & Solution',
    'projectdetail.problem': 'The Problem',
    'projectdetail.solution': 'The Solution',
    'projectdetail.features': 'Key Features',
    'projectdetail.techstack': 'Technology Stack',
    'projectdetail.frontend': 'Frontend',
    'projectdetail.backend': 'Backend',
    'projectdetail.architecture.title': 'Architecture',
    'projectdetail.architecture.section': 'System Architecture',
    'projectdetail.challenges.title': 'Challenges & Learnings',
    'projectdetail.challenges': 'Key Challenges',
    'projectdetail.learnings': 'What I Learned',
    'projectdetail.github': 'View on GitHub',
    'projectdetail.demo': 'Live Demo',
    'projectdetail.more': 'Explore More Projects',
    'projectdetail.viewall': 'View All Projects',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('language');
      return (saved === 'en' || saved === 'nl') ? saved : 'nl';
    }
    return 'nl';
  });

  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', language);
    }
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['nl']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
