import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'nl' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  nl: {
    // Navbar
    'nav.home': 'Home',
    'nav.about': 'Over Mij',
    'nav.portfolio': 'Portfolio',
    'nav.events': 'Events',
    'nav.article': 'Artikelen',

    // Hero Section
    'hero.welcome': 'Welkom in mijn',
    'hero.portfolio': 'digitale portfolio',
    'hero.role1': 'Full Stack Developer',
    'hero.role2': 'UI/UX Enthusiast',
    'hero.role3': 'Cybersecurity Enthusiast',
    'hero.description1': 'Ik transformeer ideeën naar',
    'hero.description1.highlight': 'digitale realiteit',
    'hero.description2': 'Als IT-student en passionate developer bouw ik moderne webapplicaties die niet alleen mooi zijn, maar ook',
    'hero.description2.highlight': 'innovatief en gebruiksvriendelijk',
    'hero.description3': 'Gespecialiseerd in React, TypeScript, Node.js en moderne web technologieën.',
    'hero.downloadCV': 'Download CV',
    'hero.follow': 'Te vinden op:',

    // About Section
    'about.title': 'Over Mij',
    'about.subtitle': 'Met een passie voor technologie en innovatie, ontwikkel ik moderne webapplicaties die gebruikerservaring en functionaliteit perfect combineren.',
    'about.frontend': 'Frontend Development',
    'about.frontend.desc': 'React, TypeScript, Next.js, Tailwind CSS',
    'about.backend': 'Backend Development',
    'about.backend.desc': 'Node.js, Python, Databases, API Design',
    'about.uiux': 'UI/UX Design',
    'about.uiux.desc': 'Figma, Prototyping, User Research, Design Systems',
    'about.projects': 'Projects',
    'about.projects.desc': 'Ontdek mijn innovatieve projecten van e-commerce platforms tot portfolio dashboards.',
    'about.experience': 'Experience',
    'about.experience.desc': 'Jaren ervaring in het bouwen van schaalbare webapplicaties met moderne technologieën.',
    'about.passion': 'Passion',
    'about.passion.desc': 'Gedreven door perfectie en altijd op zoek naar nieuwe uitdagingen in de digitale wereld.',
    'about.tech': 'Technologieën & Tools',

    // Skills Section
    'skills.title': 'Mijn Skills',
    'skills.subtitle': 'Een overzicht van mijn technische vaardigheden en expertise in verschillende gebieden van softwareontwikkeling.',
    'skills.learning.title': 'Altijd Leren & Groeien',
    'skills.learning.desc': 'Technologie evolueert constant, en ik ook. Ik ben altijd bezig met het leren van nieuwe frameworks, tools en best practices om voorop te blijven lopen in de wereld van webontwikkeling.',

    // Portfolio Section
    'portfolio.title': 'Mijn Portfolio',
    'portfolio.subtitle': 'Een selectie van mijn meest recente en innovatieve projecten die moderne technologieën en creatieve oplossingen combineren.',
    'portfolio.featured': 'Featured Projects',
    'portfolio.other': 'Andere Projecten',
    'portfolio.keyFeatures': 'Key Features:',
    'portfolio.viewProject': 'View Project',
    'portfolio.cta.title': 'Geïnteresseerd in samenwerking?',
    'portfolio.cta.subtitle': 'Laten we samen iets geweldigs bouwen. Neem contact op voor meer informatie over mijn projecten.',
    'portfolio.cta.button': 'Bekijk Alle Projecten',

    // Contact Section
    'contact.title': 'Laten we samenwerken',
    'contact.subtitle': 'Heb je een interessant project, een vraag over mijn werk, of wil je gewoon een gesprek? Ik hoor graag van je en ben altijd open voor nieuwe uitdagingen!',
    'contact.form.title': 'Stuur een bericht',
    'contact.form.name': 'Naam',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Onderwerp',
    'contact.form.message': 'Bericht',
    'contact.form.send': 'Verstuur Bericht',
    'contact.info': 'Contact Informatie',
    'contact.email': 'Email',
    'contact.email.desc': 'Voor projecten en samenwerking',
    'contact.linkedin': 'LinkedIn',
    'contact.linkedin.desc': 'Professioneel netwerk',
    'contact.github': 'GitHub',
    'contact.github.desc': 'Bekijk mijn code',
    'contact.availability': 'Beschikbaarheid',
    'contact.available': 'Beschikbaar voor nieuwe projecten',
    'contact.available.desc': 'Ik reageer meestal binnen 24 uur op berichten en ben altijd geïnteresseerd in uitdagende projecten.',
    'contact.expect': 'Wat kun je verwachten?',
    'contact.expect1': 'Snelle en professionele reactie',
    'contact.expect2': 'Transparante communicatie over project scope',
    'contact.expect3': 'Hoge kwaliteit code en design',
    'contact.expect4': 'Ondersteuning na oplevering',
    'contact.cta.title': 'Klaar om je idee werkelijkheid te maken?',
    'contact.cta.subtitle': 'Van concept tot realisatie - laten we samen iets geweldigs bouwen dat impact maakt.',
    'contact.cta.start': 'Start een Project',
    'contact.cta.portfolio': 'Bekijk Portfolio',

    // Footer Section
    'footer.description': 'Full-stack developer & UI/UX designer met een passie voor het bouwen van innovatieve digitale oplossingen.',
    'footer.quickLinks': 'Quick Links',
    'footer.technologies': 'Technologies',
    'footer.services': 'Diensten',
    'footer.specialties': 'Specialiteiten',
    'footer.services.web': 'Web Development',
    'footer.services.uiux': 'UI/UX Design',
    'footer.services.app': 'App Development',
    'footer.services.consulting': 'Consulting',
    'footer.spec.webapps': 'Web Apps',
    'footer.spec.uiux': 'UI/UX Design',
    'footer.spec.fullstack': 'Frontend & Backend',
    'footer.spec.databases': 'Databases',
    'footer.spec.apis': 'API\'s',
    'footer.spec.webapplications': 'Webapplicaties',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.copyright': '© 2025 Wishant Bhajan. Alle rechten voorbehouden.',

    // AboutMe Section (Homepage)
    'aboutme.intro1': 'Hoi! Ik ben Wishant, een gepassioneerde full-stack developer die moderne, innovatieve webapplicaties bouwt. Met expertise in React, TypeScript en Node.js breng ik ideeën tot leven.',
    'aboutme.intro2': 'Van concept tot deployment - ik ontwikkel complete oplossingen met oog voor design, performance en gebruikerservaring.',
    'aboutme.frontend.title': 'Frontend',
    'aboutme.frontend.text': 'React, TypeScript, Next.js',
    'aboutme.backend.title': 'Backend',
    'aboutme.backend.text': 'Node.js, Express, PostgreSQL',
    'aboutme.uiux.title': 'UI/UX Design',
    'aboutme.uiux.text': 'Figma, Tailwind, Responsive Design',
    'aboutme.readMore': 'Lees meer over mij',

    // Contact Section (Homepage)
    'contact.connect': 'Let\'s Connect',
    'contact.intro': 'Open voor nieuwe projecten en samenwerkingen. Neem gerust contact op voor een gesprek over uw volgende digitale oplossing.',
    'contact.phone': 'Telefoon',
    'contact.availability.status': 'Beschikbaar voor freelance projecten',

    // Portfolio Section (Homepage)
    'portfolio.header': 'Featured Projects',
    'portfolio.description': 'Cutting-edge solutions met moderne technologieën en innovatieve designs',
    'portfolio.filter.all': 'All Projects',
    'portfolio.filter.web': 'Web Apps',
    'portfolio.filter.ai': 'AI/ML',
    'portfolio.filter.blockchain': 'Blockchain',
    'portfolio.filter.data': 'Data Viz',
    'portfolio.status.live': 'LIVE',
    'portfolio.status.development': 'DEVELOPMENT',
    'portfolio.status.completed': 'COMPLETED',
    'portfolio.demo': 'Live Demo',
    'portfolio.github.link': 'GitHub',
    'portfolio.techTooltip': 'Click to filter',
    'portfolio.moretech': 'more',
    'portfolio.cta.header': 'Geïnteresseerd in een samenwerking?',
    'portfolio.cta.description': 'Laten we samen iets geweldigs bouwen. Neem contact op voor projecten, samenwerkingen of gewoon een gesprek over technologie.',
    'portfolio.homepage.cta.button': 'Start een Project',

    // Project Data
    'project1.title': 'E-commerce Platform',
    'project1.desc': 'Modern webshop met AI-powered recommendations',
    'project1.extDesc': 'Een volledig functionele webshop met React, Node.js en Stripe integratie. Bevat gebruikersbeheer, productcatalogus, winkelwagen en veilige betalingen.',
    'project1.feature1': 'Responsive Design',
    'project1.feature2': 'Payment Integration',
    'project1.feature3': 'User Authentication',
    'project1.feature4': 'Admin Dashboard',
    'project2.title': 'AI Dashboard',
    'project2.desc': 'Real-time analytics met machine learning',
    'project2.extDesc': 'Interactive dashboard voor portfolio management met real-time data visualisatie, analytics en content management systeem.',
    'project2.feature1': 'Real-time Analytics',
    'project2.feature2': 'Content Management',
    'project2.feature3': 'Data Visualization',
    'project2.feature4': 'Multi-user Support',
    'project3.title': 'Blockchain Wallet',
    'project3.desc': 'Secure crypto wallet met multi-chain support',
    'project3.feature1': 'Multi-chain',
    'project3.feature2': 'Hardware Wallet',
    'project3.feature3': 'DeFi Integration',
    'project4.title': 'Task Management',
    'project4.desc': 'Productivity app met AI assistant',
    'project4.feature1': 'Drag & Drop',
    'project4.feature2': 'Team Collaboration',
    'project4.feature3': 'AI Suggestions',
    'project5.title': 'Weather Dashboard',
    'project5.desc': 'Real-time weather met predictive analytics',
    'project5.feature1': 'Interactive Maps',
    'project5.feature2': 'Forecasting',
    'project5.feature3': 'Alerts',
    'project6.title': 'Social Platform',
    'project6.desc': 'Next-gen social media met privacy focus',
    'project6.feature1': 'End-to-end Encryption',
    'project6.feature2': 'Live Chat',
    'project6.feature3': 'Stories',

    // Skills Categories
    'skills.category.frontend': 'Frontend Development',
    'skills.category.backend': 'Backend Development',
    'skills.category.tools': 'Tools & Technologies',
    'skills.category.languages': 'Programming Languages',

    // ContactPage
    'contactpage.hero.title': 'Let\'s Connect',
    'contactpage.hero.subtitle': 'Heb je een project in gedachten? Laten we samen iets geweldigs bouwen.',
    'contactpage.form.title': 'Send a Message',
    'contactpage.form.name.label': 'Name',
    'contactpage.form.name.placeholder': 'John Doe',
    'contactpage.form.email.label': 'Email',
    'contactpage.form.email.placeholder': 'john@example.com',
    'contactpage.form.subject.label': 'Subject',
    'contactpage.form.subject.placeholder': 'Select a subject',
    'contactpage.form.subject.project': 'New Project',
    'contactpage.form.subject.collaboration': 'Collaboration',
    'contactpage.form.subject.consultation': 'Consultation',
    'contactpage.form.subject.other': 'Other',
    'contactpage.form.message.label': 'Message',
    'contactpage.form.message.placeholder': 'Tell me about your project...',
    'contactpage.form.submit': 'Send Message',
    'contactpage.form.sending': 'Sending...',
    'contactpage.form.success': 'Message sent successfully!',
    'contactpage.form.error': 'Something went wrong. Please try again.',
    'contactpage.info.title': 'Get in Touch',
    'contactpage.info.location': 'Location',
    'contactpage.info.netherlands': 'Netherlands',
    'contactpage.social.title': 'Connect on Social',
    'contactpage.social.twitter': 'Twitter',
    'contactpage.social.discord': 'Discord',
    'contactpage.availability.title': 'Currently Available',
    'contactpage.availability.desc': 'I\'m open for freelance projects and full-time opportunities. Response time: usually within 24 hours.',
    'contactpage.faq.title': 'Frequently Asked Questions',
    'contactpage.faq.subtitle': 'Antwoorden op veelgestelde vragen',
    'contactpage.faq1.q': 'What services do you offer?',
    'contactpage.faq1.a': 'Full stack web development, UI/UX design, API development, security auditing, and technical consulting.',
    'contactpage.faq2.q': 'What is your typical project timeline?',
    'contactpage.faq2.a': 'Project timelines vary based on complexity. Small projects: 2-4 weeks, Medium: 1-3 months, Large: 3-6 months.',
    'contactpage.faq3.q': 'Do you work remotely?',
    'contactpage.faq3.a': 'Yes! I work with clients globally and am comfortable with remote collaboration tools and async communication.',
    'contactpage.faq4.q': 'What are your rates?',
    'contactpage.faq4.a': 'Rates depend on project scope and complexity. Contact me for a custom quote tailored to your needs.',

    // AboutPage
    'aboutpage.hero.title': 'Over Mij',
    'aboutpage.hero.subtitle': 'Een gepassioneerde Full Stack Developer met focus op cybersecurity, moderne web technologieën en het creëren van innovatieve digitale ervaringen.',
    'aboutpage.role.developer': 'Developer',
    'aboutpage.role.designer': 'Designer',
    'aboutpage.role.innovator': 'Innovator',
    'aboutpage.role.problemsolver': 'Problem Solver',
    'aboutpage.tab.journey': 'Mijn Reis',
    'aboutpage.tab.expertise': 'Expertise',
    'aboutpage.tab.values': 'Waarden',
    'aboutpage.journey.2020.event': 'Begonnen met programmeren',
    'aboutpage.journey.2020.desc': 'Eerste stappen in web development',
    'aboutpage.journey.2021.event': 'Deep dive in React & TypeScript',
    'aboutpage.journey.2021.desc': 'Moderne frontend frameworks',
    'aboutpage.journey.2022.event': 'Full Stack Development',
    'aboutpage.journey.2022.desc': 'Backend, databases en cloud',
    'aboutpage.journey.2023.event': 'Cybersecurity Focus',
    'aboutpage.journey.2023.desc': 'Secure coding practices',
    'aboutpage.journey.2024.event': 'UI/UX Specialist',
    'aboutpage.journey.2024.desc': 'Design systems en user experience',
    'aboutpage.expertise.frontend': 'Frontend Architecture',
    'aboutpage.expertise.backend': 'Backend Development',
    'aboutpage.expertise.cybersecurity': 'Cybersecurity',
    'aboutpage.expertise.uiux': 'UI/UX Design',
    'aboutpage.expertise.devops': 'DevOps & Cloud',
    'aboutpage.value.security.title': 'Security First',
    'aboutpage.value.security.desc': 'Elke lijn code met beveiliging in gedachten',
    'aboutpage.value.performance.title': 'Performance',
    'aboutpage.value.performance.desc': 'Snelle, geoptimaliseerde applicaties',
    'aboutpage.value.ux.title': 'User Experience',
    'aboutpage.value.ux.desc': 'Intuïtieve en mooie interfaces',
    'aboutpage.value.innovation.title': 'Innovation',
    'aboutpage.value.innovation.desc': 'Altijd op zoek naar betere oplossingen',
    'aboutpage.cta.title': 'Laten We Samen Bouwen',
    'aboutpage.cta.subtitle': 'Op zoek naar een developer die jouw visie kan realiseren?',
    'aboutpage.cta.button': 'Bekijk Portfolio',

    // Featured Projects & Skills Section
    'featured.projects.title': 'Uitgelichte Projecten',
    'featured.projects.description': 'Geavanceerde oplossingen met moderne technologieën',
    'featured.skills.title': 'Technische Vaardigheden',
    'featured.skills.description': 'Expertise in moderne technologieën en frameworks',
    'featured.viewAllProjects': 'Bekijk Alle Projecten',

    // Project Cards
    'featured.project1.title': 'CyberGuard Pro',
    'featured.project1.desc': 'Geavanceerd netwerk security monitoring systeem met real-time threat detection en geautomatiseerde response mogelijkheden',
    'featured.project1.label': 'Live',
    'featured.project2.title': 'Data Vault',
    'featured.project2.desc': 'Versleutelde cloud opslag met zero-knowledge architectuur',
    'featured.project2.label': 'In Ontwikkeling',
    'featured.project3.title': 'AI Assistent',
    'featured.project3.desc': 'Slim automatiserings platform aangedreven door machine learning',
    'featured.project3.label': 'Featured',
    'featured.project4.title': 'Blockchain Wallet',
    'featured.project4.desc': 'Veilige crypto wallet met multi-chain support en DeFi integratie',
    'featured.project4.label': 'Beta',
    'featured.project5.title': 'Task Manager',
    'featured.project5.desc': 'Productiviteits app met AI suggesties',
    'featured.project5.label': 'Live',
    'featured.project6.title': 'Weather Dashboard',
    'featured.project6.desc': 'Real-time weer analytics met voorspellende modellen',
    'featured.project6.label': 'Live',

    // Skills
    'featured.skill.ai': 'Alle Programmeertalen',
    'featured.skill.ai.note': 'Ik weet hoe ik met AI moet praten',
    'featured.skill.react': 'React / Next.js',
    'featured.skill.typescript': 'TypeScript',
    'featured.skill.csharp': 'C#',
    'featured.skill.nodejs': 'Node.js',
    'featured.skill.python': 'Python',
    'featured.skill.cybersecurity': 'Cybersecurity',
    'featured.skill.databases': 'Databases',
    'featured.skill.docker': 'Docker / K8s',
    'featured.skill.ml': 'Machine Learning',
    'featured.skill.other': 'Overige technologieën',

    // Skill Categories
    'featured.category.ai': 'AI',
    'featured.category.frontend': 'Frontend',
    'featured.category.backend': 'Backend',
    'featured.category.security': 'Security',
    'featured.category.database': 'Database',
    'featured.category.devops': 'DevOps',
    'featured.category.tools': 'Tools',

    // Skill Stats
    'featured.stats.technologies': 'Technologieën',
    'featured.stats.experience': 'Jaar Ervaring',
    'featured.stats.projects': 'Projecten',

    // About Section (Homepage)
    'aboutsection.title': 'Over Mij',
    'aboutsection.subtitle': '3e jaars Informatica student met een passie voor cybersecurity en innovatieve weboplossingen. Ik combineer creativiteit met technische expertise om veilige en gebruiksvriendelijke applicaties te bouwen.',
    'aboutsection.terminal.name': 'Naam: Wishant Bhajan',
    'aboutsection.terminal.age': 'Leeftijd: 20',
    'aboutsection.terminal.location': 'Locatie: Rotterdam, NL',
    'aboutsection.terminal.role': 'Rol: Student Informatica 3e jaars',
    'aboutsection.terminal.status': 'Status: Beschikbaar voor werk',
    'aboutsection.terminal.passion': 'Passie: Cybersecurity & Innovatie',
    'aboutsection.terminal.experience': 'Ervaring: 3+ jaar',
    'aboutsection.button': 'Meer Over Mij',
    'aboutsection.profilecard.name': 'Wishant Bhajan',
    'aboutsection.profilecard.title': 'Software Engineer',
    'aboutsection.profilecard.status': 'Beschikbaar voor werk',
    'aboutsection.profilecard.contact': 'Contact',
  },
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.about': 'About Me',
    'nav.portfolio': 'Portfolio',
    'nav.events': 'Events',
    'nav.article': 'Articles',

    // Hero Section
    'hero.welcome': 'Welcome to my',
    'hero.portfolio': 'digital portfolio',
    'hero.role1': 'Full Stack Developer',
    'hero.role2': 'UI/UX Enthusiast',
    'hero.role3': 'Cybersecurity Enthusiast',
    'hero.description1': 'I transform ideas into',
    'hero.description1.highlight': 'digital reality',
    'hero.description2': 'As an IT student and passionate developer, I build modern web applications that are not only beautiful, but also',
    'hero.description2.highlight': 'innovative and user-friendly',
    'hero.description3': 'Specialized in React, TypeScript, Node.js and modern web technologies.',
    'hero.downloadCV': 'Download CV',
    'hero.follow': 'Find me on:',

    // About Section
    'about.title': 'About Me',
    'about.subtitle': 'With a passion for technology and innovation, I develop modern web applications that perfectly combine user experience and functionality.',
    'about.frontend': 'Frontend Development',
    'about.frontend.desc': 'React, TypeScript, Next.js, Tailwind CSS',
    'about.backend': 'Backend Development',
    'about.backend.desc': 'Node.js, Python, Databases, API Design',
    'about.uiux': 'UI/UX Design',
    'about.uiux.desc': 'Figma, Prototyping, User Research, Design Systems',
    'about.projects': 'Projects',
    'about.projects.desc': 'Discover my innovative projects from e-commerce platforms to portfolio dashboards.',
    'about.experience': 'Experience',
    'about.experience.desc': 'Years of experience building scalable web applications with modern technologies.',
    'about.passion': 'Passion',
    'about.passion.desc': 'Driven by perfection and always looking for new challenges in the digital world.',
    'about.tech': 'Technologies & Tools',

    // Skills Section
    'skills.title': 'My Skills',
    'skills.subtitle': 'An overview of my technical skills and expertise in various areas of software development.',
    'skills.learning.title': 'Always Learning & Growing',
    'skills.learning.desc': 'Technology is constantly evolving, and so am I. I am always learning new frameworks, tools and best practices to stay ahead in the world of web development.',

    // Portfolio Section
    'portfolio.title': 'My Portfolio',
    'portfolio.subtitle': 'A selection of my most recent and innovative projects that combine modern technologies and creative solutions.',
    'portfolio.featured': 'Featured Projects',
    'portfolio.other': 'Other Projects',
    'portfolio.keyFeatures': 'Key Features:',
    'portfolio.viewProject': 'View Project',
    'portfolio.cta.title': 'Interested in collaboration?',
    'portfolio.cta.subtitle': "Let's build something amazing together. Contact me for more information about my projects.",
    'portfolio.cta.button': 'View All Projects',

    // Contact Section
    'contact.title': "Let's work together",
    'contact.subtitle': 'Have an interesting project, a question about my work, or just want to chat? I would love to hear from you and am always open to new challenges!',
    'contact.form.title': 'Send a message',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.info': 'Contact Information',
    'contact.email': 'Email',
    'contact.email.desc': 'For projects and collaboration',
    'contact.linkedin': 'LinkedIn',
    'contact.linkedin.desc': 'Professional network',
    'contact.github': 'GitHub',
    'contact.github.desc': 'View my code',
    'contact.availability': 'Availability',
    'contact.available': 'Available for new projects',
    'contact.available.desc': 'I usually respond within 24 hours and am always interested in challenging projects.',
    'contact.expect': 'What can you expect?',
    'contact.expect1': 'Fast and professional response',
    'contact.expect2': 'Transparent communication about project scope',
    'contact.expect3': 'High quality code and design',
    'contact.expect4': 'Support after delivery',
    'contact.cta.title': 'Ready to bring your idea to life?',
    'contact.cta.subtitle': 'From concept to realization - let\'s build something amazing together that makes an impact.',
    'contact.cta.start': 'Start a Project',
    'contact.cta.portfolio': 'View Portfolio',

    // Footer Section
    'footer.description': 'Full-stack developer & UI/UX designer with a passion for building innovative digital solutions.',
    'footer.quickLinks': 'Quick Links',
    'footer.technologies': 'Technologies',
    'footer.services': 'Services',
    'footer.specialties': 'Specialties',
    'footer.services.web': 'Web Development',
    'footer.services.uiux': 'UI/UX Design',
    'footer.services.app': 'App Development',
    'footer.services.consulting': 'Consulting',
    'footer.spec.webapps': 'Web Apps',
    'footer.spec.uiux': 'UI/UX Design',
    'footer.spec.fullstack': 'Frontend & Backend',
    'footer.spec.databases': 'Databases',
    'footer.spec.apis': 'API\'s',
    'footer.spec.webapplications': 'Web Applications',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.copyright': '© 2025 Wishant Bhajan. All rights reserved.',

    // AboutMe Section (Homepage)
    'aboutme.intro1': 'Hi! I\'m Wishant, a passionate full-stack developer building modern, innovative web applications. With expertise in React, TypeScript and Node.js, I bring ideas to life.',
    'aboutme.intro2': 'From concept to deployment - I develop complete solutions with an eye for design, performance and user experience.',
    'aboutme.frontend.title': 'Frontend',
    'aboutme.frontend.text': 'React, TypeScript, Next.js',
    'aboutme.backend.title': 'Backend',
    'aboutme.backend.text': 'Node.js, Express, PostgreSQL',
    'aboutme.uiux.title': 'UI/UX Design',
    'aboutme.uiux.text': 'Figma, Tailwind, Responsive Design',
    'aboutme.readMore': 'Read more about me',

    // Contact Section (Homepage)
    'contact.connect': 'Let\'s Connect',
    'contact.intro': 'Open for new projects and collaborations. Feel free to contact me for a conversation about your next digital solution.',
    'contact.phone': 'Phone',
    'contact.availability.status': 'Available for freelance projects',

    // Portfolio Section (Homepage)
    'portfolio.header': 'Featured Projects',
    'portfolio.description': 'Cutting-edge solutions with modern technologies and innovative designs',
    'portfolio.filter.all': 'All Projects',
    'portfolio.filter.web': 'Web Apps',
    'portfolio.filter.ai': 'AI/ML',
    'portfolio.filter.blockchain': 'Blockchain',
    'portfolio.filter.data': 'Data Viz',
    'portfolio.status.live': 'LIVE',
    'portfolio.status.development': 'DEVELOPMENT',
    'portfolio.status.completed': 'COMPLETED',
    'portfolio.demo': 'Live Demo',
    'portfolio.github.link': 'GitHub',
    'portfolio.techTooltip': 'Click to filter',
    'portfolio.moretech': 'more',
    'portfolio.cta.header': 'Interested in collaboration?',
    'portfolio.cta.description': 'Let\'s build something amazing together. Contact me for projects, collaborations or just a chat about technology.',
    'portfolio.homepage.cta.button': 'Start a Project',

    // Project Data
    'project1.title': 'E-commerce Platform',
    'project1.desc': 'Modern webshop with AI-powered recommendations',
    'project1.extDesc': 'A fully functional webshop with React, Node.js and Stripe integration. Includes user management, product catalog, shopping cart and secure payments.',
    'project1.feature1': 'Responsive Design',
    'project1.feature2': 'Payment Integration',
    'project1.feature3': 'User Authentication',
    'project1.feature4': 'Admin Dashboard',
    'project2.title': 'AI Dashboard',
    'project2.desc': 'Real-time analytics with machine learning',
    'project2.extDesc': 'Interactive dashboard for portfolio management with real-time data visualization, analytics and content management system.',
    'project2.feature1': 'Real-time Analytics',
    'project2.feature2': 'Content Management',
    'project2.feature3': 'Data Visualization',
    'project2.feature4': 'Multi-user Support',
    'project3.title': 'Blockchain Wallet',
    'project3.desc': 'Secure crypto wallet with multi-chain support',
    'project3.feature1': 'Multi-chain',
    'project3.feature2': 'Hardware Wallet',
    'project3.feature3': 'DeFi Integration',
    'project4.title': 'Task Management',
    'project4.desc': 'Productivity app with AI assistant',
    'project4.feature1': 'Drag & Drop',
    'project4.feature2': 'Team Collaboration',
    'project4.feature3': 'AI Suggestions',
    'project5.title': 'Weather Dashboard',
    'project5.desc': 'Real-time weather with predictive analytics',
    'project5.feature1': 'Interactive Maps',
    'project5.feature2': 'Forecasting',
    'project5.feature3': 'Alerts',
    'project6.title': 'Social Platform',
    'project6.desc': 'Next-gen social media with privacy focus',
    'project6.feature1': 'End-to-end Encryption',
    'project6.feature2': 'Live Chat',
    'project6.feature3': 'Stories',

    // Skills Categories
    'skills.category.frontend': 'Frontend Development',
    'skills.category.backend': 'Backend Development',
    'skills.category.tools': 'Tools & Technologies',
    'skills.category.languages': 'Programming Languages',

    // ContactPage
    'contactpage.hero.title': 'Let\'s Connect',
    'contactpage.hero.subtitle': 'Have a project in mind? Let\'s build something amazing together.',
    'contactpage.form.title': 'Send a Message',
    'contactpage.form.name.label': 'Name',
    'contactpage.form.name.placeholder': 'John Doe',
    'contactpage.form.email.label': 'Email',
    'contactpage.form.email.placeholder': 'john@example.com',
    'contactpage.form.subject.label': 'Subject',
    'contactpage.form.subject.placeholder': 'Select a subject',
    'contactpage.form.subject.project': 'New Project',
    'contactpage.form.subject.collaboration': 'Collaboration',
    'contactpage.form.subject.consultation': 'Consultation',
    'contactpage.form.subject.other': 'Other',
    'contactpage.form.message.label': 'Message',
    'contactpage.form.message.placeholder': 'Tell me about your project...',
    'contactpage.form.submit': 'Send Message',
    'contactpage.form.sending': 'Sending...',
    'contactpage.form.success': 'Message sent successfully!',
    'contactpage.form.error': 'Something went wrong. Please try again.',
    'contactpage.info.title': 'Get in Touch',
    'contactpage.info.location': 'Location',
    'contactpage.info.netherlands': 'Netherlands',
    'contactpage.social.title': 'Connect on Social',
    'contactpage.social.twitter': 'Twitter',
    'contactpage.social.discord': 'Discord',
    'contactpage.availability.title': 'Currently Available',
    'contactpage.availability.desc': 'I\'m open for freelance projects and full-time opportunities. Response time: usually within 24 hours.',
    'contactpage.faq.title': 'Frequently Asked Questions',
    'contactpage.faq.subtitle': 'Answers to frequently asked questions',
    'contactpage.faq1.q': 'What services do you offer?',
    'contactpage.faq1.a': 'Full stack web development, UI/UX design, API development, security auditing, and technical consulting.',
    'contactpage.faq2.q': 'What is your typical project timeline?',
    'contactpage.faq2.a': 'Project timelines vary based on complexity. Small projects: 2-4 weeks, Medium: 1-3 months, Large: 3-6 months.',
    'contactpage.faq3.q': 'Do you work remotely?',
    'contactpage.faq3.a': 'Yes! I work with clients globally and am comfortable with remote collaboration tools and async communication.',
    'contactpage.faq4.q': 'What are your rates?',
    'contactpage.faq4.a': 'Rates depend on project scope and complexity. Contact me for a custom quote tailored to your needs.',

    // AboutPage
    'aboutpage.hero.title': 'About Me',
    'aboutpage.hero.subtitle': 'A passionate Full Stack Developer focused on cybersecurity, modern web technologies and creating innovative digital experiences.',
    'aboutpage.role.developer': 'Developer',
    'aboutpage.role.designer': 'Designer',
    'aboutpage.role.innovator': 'Innovator',
    'aboutpage.role.problemsolver': 'Problem Solver',
    'aboutpage.tab.journey': 'My Journey',
    'aboutpage.tab.expertise': 'Expertise',
    'aboutpage.tab.values': 'Values',
    'aboutpage.journey.2020.event': 'Started programming',
    'aboutpage.journey.2020.desc': 'First steps in web development',
    'aboutpage.journey.2021.event': 'Deep dive in React & TypeScript',
    'aboutpage.journey.2021.desc': 'Modern frontend frameworks',
    'aboutpage.journey.2022.event': 'Full Stack Development',
    'aboutpage.journey.2022.desc': 'Backend, databases and cloud',
    'aboutpage.journey.2023.event': 'Cybersecurity Focus',
    'aboutpage.journey.2023.desc': 'Secure coding practices',
    'aboutpage.journey.2024.event': 'UI/UX Specialist',
    'aboutpage.journey.2024.desc': 'Design systems and user experience',
    'aboutpage.expertise.frontend': 'Frontend Architecture',
    'aboutpage.expertise.backend': 'Backend Development',
    'aboutpage.expertise.cybersecurity': 'Cybersecurity',
    'aboutpage.expertise.uiux': 'UI/UX Design',
    'aboutpage.expertise.devops': 'DevOps & Cloud',
    'aboutpage.value.security.title': 'Security First',
    'aboutpage.value.security.desc': 'Every line of code with security in mind',
    'aboutpage.value.performance.title': 'Performance',
    'aboutpage.value.performance.desc': 'Fast, optimized applications',
    'aboutpage.value.ux.title': 'User Experience',
    'aboutpage.value.ux.desc': 'Intuitive and beautiful interfaces',
    'aboutpage.value.innovation.title': 'Innovation',
    'aboutpage.value.innovation.desc': 'Always looking for better solutions',
    'aboutpage.cta.title': 'Let\'s Build Together',
    'aboutpage.cta.subtitle': 'Looking for a developer who can realize your vision?',
    'aboutpage.cta.button': 'View Portfolio',

    // Featured Projects & Skills Section
    'featured.projects.title': 'Featured Projects',
    'featured.projects.description': 'Cutting-edge solutions with modern technologies',
    'featured.skills.title': 'Technical Skills',
    'featured.skills.description': 'Expertise in modern technologies and frameworks',
    'featured.viewAllProjects': 'View All Projects',

    // Project Cards
    'featured.project1.title': 'CyberGuard Pro',
    'featured.project1.desc': 'Advanced network security monitoring system with real-time threat detection and automated response capabilities',
    'featured.project1.label': 'Live',
    'featured.project2.title': 'Data Vault',
    'featured.project2.desc': 'Encrypted cloud storage with zero-knowledge architecture',
    'featured.project2.label': 'In Development',
    'featured.project3.title': 'AI Assistant',
    'featured.project3.desc': 'Smart automation platform powered by machine learning',
    'featured.project3.label': 'Featured',
    'featured.project4.title': 'Blockchain Wallet',
    'featured.project4.desc': 'Secure crypto wallet with multi-chain support and DeFi integration',
    'featured.project4.label': 'Beta',
    'featured.project5.title': 'Task Manager',
    'featured.project5.desc': 'Productivity app with AI suggestions',
    'featured.project5.label': 'Live',
    'featured.project6.title': 'Weather Dashboard',
    'featured.project6.desc': 'Real-time weather analytics with predictive models',
    'featured.project6.label': 'Live',

    // Skills
    'featured.skill.ai': 'All Programming Languages',
    'featured.skill.ai.note': 'I know how to talk to AI',
    'featured.skill.react': 'React / Next.js',
    'featured.skill.typescript': 'TypeScript',
    'featured.skill.csharp': 'C#',
    'featured.skill.nodejs': 'Node.js',
    'featured.skill.python': 'Python',
    'featured.skill.cybersecurity': 'Cybersecurity',
    'featured.skill.databases': 'Databases',
    'featured.skill.docker': 'Docker / K8s',
    'featured.skill.ml': 'Machine Learning',
    'featured.skill.other': 'Other technologies',

    // Skill Categories
    'featured.category.ai': 'AI',
    'featured.category.frontend': 'Frontend',
    'featured.category.backend': 'Backend',
    'featured.category.security': 'Security',
    'featured.category.database': 'Database',
    'featured.category.devops': 'DevOps',
    'featured.category.tools': 'Tools',

    // Skill Stats
    'featured.stats.technologies': 'Technologies',
    'featured.stats.experience': 'Years Exp',
    'featured.stats.projects': 'Projects',

    // About Section (Homepage)
    'aboutsection.title': 'About Me',
    'aboutsection.subtitle': '3rd year Computer Science student with a passion for cybersecurity and innovative web solutions. I combine creativity with technical expertise to build secure and user-friendly applications.',
    'aboutsection.terminal.name': 'Name: Wishant Bhajan',
    'aboutsection.terminal.age': 'Age: 20',
    'aboutsection.terminal.location': 'Location: Rotterdam, NL',
    'aboutsection.terminal.role': 'Role: 3rd Year Computer Science Student',
    'aboutsection.terminal.status': 'Status: Available for work',
    'aboutsection.terminal.passion': 'Passion: Cybersecurity & Innovation',
    'aboutsection.terminal.experience': 'Experience: 3+ years',
    'aboutsection.button': 'More About Me',
    'aboutsection.profilecard.name': 'Wishant Bhajan',
    'aboutsection.profilecard.title': 'Software Engineer',
    'aboutsection.profilecard.status': 'Available for work',
    'aboutsection.profilecard.contact': 'Contact',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'nl') ? saved : 'nl';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['nl']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
